# -*- coding: utf-8 -*-
"""
تنظیمات عمومی بازی، لیست ۱۷ کشور، مقادیر اولیه و کاتالوگ جامع دارایی‌های نظامی اختصاصی تمام کشورها (Country Assets Catalog).
شامل تفکیک دقیق سلاح‌های تولید بومی (producible=True) از سلاح‌های وارداتی (producible=False).
"""

import os

# ===== توکن بات =====
BOT_TOKEN = os.environ.get("BOT_TOKEN", "TOKEN_ATO_EINJA_BEZAR")

# ===== آیدی عددی ادمین اصلی =====
admin_env = os.environ.get("ADMIN_IDS", "")
if admin_env:
    ADMIN_IDS = [int(x.strip()) for x in admin_env.split(",") if x.strip().isdigit()]
else:
    ADMIN_IDS = [
        8052987465,
    ]

# ===== لیست کامل کشورهای قابل انتخاب در بازی (۱۷ کشور) =====
COUNTRIES = {
    "iran":    {"name": "ایران",    "flag": "🇮🇷"},
    "germany": {"name": "آلمان",    "flag": "🇩🇪"},
    "qatar":   {"name": "قطر",      "flag": "🇶🇦"},
    "usa":     {"name": "آمریکا",   "flag": "🇺🇸"},
    "russia":  {"name": "روسیه",    "flag": "🇷🇺"},
    "china":   {"name": "چین",      "flag": "🇨🇳"},
    "france":  {"name": "فرانسه",   "flag": "🇫🇷"},
    "uk":      {"name": "انگلیس",   "flag": "🇬🇧"},
    "japan":   {"name": "ژاپن",     "flag": "🇯🇵"},
    "turkey":  {"name": "ترکیه",    "flag": "🇹🇷"},
    "saudi":   {"name": "عربستان",  "flag": "🇸🇦"},
    "ukraine": {"name": "اوکراین",  "flag": "🇺🇦"},
    "india":   {"name": "هند",      "flag": "🇮🇳"},
    "brazil":  {"name": "برزیل",    "flag": "🇧🇷"},
    "egypt":   {"name": "مصر",      "flag": "🇪🇬"},
    "uae":     {"name": "امارات",   "flag": "🇦🇪"},
    "israel":  {"name": "اسرائیل",  "flag": "🇮🇱"},
}

# ===== مقادیر اولیه عمومی کشورها =====
STARTING_VALUES = {
    "population": 20_000_000,
    "treasury": 40_000_000,
    "tax_income": 8_000_000,
    "daily_income": 15_000_000,
    "gold": 300,
    "gold_daily": 40,
    "oil_reserves": 100_000_000,
    "oil_production": 1_500_000,
    "grain": 100,
    "electricity": 130,
    "active_personnel": 200_000,
    "reserve_personnel": 500_000,
}

# ===== مقادیر اختصاصی و دقیق اقتصادی و انسانی تمام کشورها =====
COUNTRY_STARTING_OVERRIDES = {
    "usa": {
        "population": 340_000_000,
        "treasury": 80_000_000,
        "tax_income": 12_000_000,
        "daily_income": 8_000_000,
        "gold": 500,
        "gold_daily": 60,
        "oil_reserves": 250_000_000,
        "oil_production": 5_000_000,
        "grain": 50,
        "electricity": 145,
        "active_personnel": 1_300_000,
        "reserve_personnel": 800_000,
    },
    "israel": {
        "population": 10_000_000,
        "treasury": 18_000_000,
        "tax_income": 7_000_000,
        "daily_income": 4_000_000,
        "gold": 200,
        "gold_daily": 40,
        "oil_reserves": 12_000_000,
        "oil_production": 1_000,
        "grain": 100,
        "electricity": 120,
        "active_personnel": 170_000,
        "reserve_personnel": 450_000,
    },
    "iran": {
        "population": 90_000_000,
        "treasury": 45_000_000,
        "tax_income": 7_000_000,
        "daily_income": 14_000_000,
        "gold": 250,
        "gold_daily": 50,
        "oil_reserves": 250_000_000,
        "oil_production": 4_000_000,
        "grain": 35,
        "electricity": 130,
        "active_personnel": 610_000,
        "reserve_personnel": 1_200_000,
    },
    "germany": {
        "population": 84_000_000,
        "treasury": 55_000_000,
        "tax_income": 10_000_000,
        "daily_income": 18_000_000,
        "gold": 350,
        "gold_daily": 50,
        "oil_reserves": 40_000_000,
        "oil_production": 1_000_000,
        "grain": 45,
        "electricity": 155,
        "active_personnel": 185_000,
        "reserve_personnel": 800_000,
    },
    "china": {
        "population": 1_400_000_000,
        "treasury": 120_000_000,
        "tax_income": 18_000_000,
        "daily_income": 25_000_000,
        "gold": 700,
        "gold_daily": 80,
        "oil_reserves": 250_000_000,
        "oil_production": 4_500_000,
        "grain": 60,
        "electricity": 155,
        "active_personnel": 2_000_000,
        "reserve_personnel": 1_000_000,
    },
    "russia": {
        "population": 144_000_000,
        "treasury": 55_000_000,
        "tax_income": 12_000_000,
        "daily_income": 16_000_000,
        "gold": 400,
        "gold_daily": 60,
        "oil_reserves": 375_000_000,
        "oil_production": 4_000_000,
        "grain": 40,
        "electricity": 145,
        "active_personnel": 1_320_000,
        "reserve_personnel": 2_000_000,
    },
    "uk": {
        "population": 69_000_000,
        "treasury": 50_000_000,
        "tax_income": 10_000_000,
        "daily_income": 17_000_000,
        "gold": 350,
        "gold_daily": 50,
        "oil_reserves": 25_000_000,
        "oil_production": 1_000_000,
        "grain": 40,
        "electricity": 150,
        "active_personnel": 185_000,
        "reserve_personnel": 900_000,
    }
}

# ===== دسته‌بندی‌های دارایی‌های نظامی =====
ASSET_CATEGORIES = {
    "Aircraft":     ("✈️ نیروی هوایی", "فروند"),
    "Missiles":     ("🚀 موشکی", "قبضه"),
    "Air Defense":  ("🛡️ پدافند هوایی", "سامانه"),
    "Navy":         ("🚢 نیروی دریایی", "فروند"),
    "Ground Forces":("🚛 نیروی زمینی", "دستگاه"),
    "UAV":          ("🛩️ پهپادها", "فروند"),
    "Artillery":    ("🎯 توپخانه", "قبضه"),
}

# ===== کاتالوگ دقیق و جامع تجهیزات نظامی تمام کشورها =====
COUNTRY_EQUIPMENT_CATALOG = {

    # 🇺🇸 ایالات متحده آمریکا (USA)
    "usa": [
        # نیروی هوایی
        {"key": "f35a",           "name": "F-35A Lightning II",    "category": "Aircraft",     "price": 15_000_000, "initial": 400,  "maint": 50_000, "producible": True},
        {"key": "f35b",           "name": "F-35B Lightning II",    "category": "Aircraft",     "price": 16_000_000, "initial": 100,  "maint": 55_000, "producible": True},
        {"key": "f35c",           "name": "F-35C Lightning II",    "category": "Aircraft",     "price": 17_000_000, "initial": 80,   "maint": 60_000, "producible": True},
        {"key": "f22",            "name": "F-22 Raptor",          "category": "Aircraft",     "price": 25_000_000, "initial": 180,  "maint": 80_000, "producible": True},
        {"key": "f15e",           "name": "F-15E Strike Eagle",   "category": "Aircraft",     "price": 12_000_000, "initial": 220,  "maint": 35_000, "producible": True},
        {"key": "f15ex",          "name": "F-15EX Eagle II",      "category": "Aircraft",     "price": 15_000_000, "initial": 20,   "maint": 40_000, "producible": True},
        {"key": "f16",            "name": "F-16 Fighting Falcon", "category": "Aircraft",     "price": 8_000_000,  "initial": 700,  "maint": 20_000, "producible": True},
        {"key": "fa18ef",         "name": "F/A-18E/F Super Hornet","category": "Aircraft",    "price": 10_000_000, "initial": 550,  "maint": 30_000, "producible": True},
        {"key": "b1b",            "name": "B-1B Lancer Bomber",   "category": "Aircraft",     "price": 35_000_000, "initial": 40,   "maint": 110_000,"producible": True},
        {"key": "b2",             "name": "B-2 Spirit Bomber",    "category": "Aircraft",     "price": 50_000_000, "initial": 20,   "maint": 150_000,"producible": True},
        {"key": "b52h",           "name": "B-52H Stratofortress", "category": "Aircraft",     "price": 30_000_000, "initial": 70,   "maint": 100_000,"producible": True},
        {"key": "c17",            "name": "C-17 Globemaster III", "category": "Aircraft",     "price": 20_000_000, "initial": 220,  "maint": 45_000, "producible": True},
        {"key": "c130",           "name": "C-130 Hercules",       "category": "Aircraft",     "price": 6_000_000,  "initial": 300,  "maint": 15_000, "producible": True},
        {"key": "c5m",            "name": "C-5M Galaxy",          "category": "Aircraft",     "price": 30_000_000, "initial": 50,   "maint": 80_000, "producible": True},
        {"key": "kc135",          "name": "KC-135 Stratotanker",  "category": "Aircraft",     "price": 8_000_000,  "initial": 380,  "maint": 20_000, "producible": True},
        {"key": "kc46",           "name": "KC-46 Pegasus",        "category": "Aircraft",     "price": 12_000_000, "initial": 100,  "maint": 25_000, "producible": True},
        {"key": "e3_sentry",      "name": "E-3 Sentry AWACS",     "category": "Aircraft",     "price": 25_000_000, "initial": 20,   "maint": 50_000, "producible": True},
        {"key": "e7_wedgetail",   "name": "E-7 Wedgetail AWACS",  "category": "Aircraft",     "price": 30_000_000, "initial": 10,   "maint": 60_000, "producible": True},
        {"key": "rc135",          "name": "RC-135 Rivet Joint",   "category": "Aircraft",     "price": 20_000_000, "initial": 20,   "maint": 40_000, "producible": True},
        {"key": "u2_dragon",      "name": "U-2 Dragon Lady",      "category": "Aircraft",     "price": 15_000_000, "initial": 20,   "maint": 30_000, "producible": True},
        {"key": "ah64e",          "name": "AH-64E Apache",        "category": "Aircraft",     "price": 5_000_000,  "initial": 800,  "maint": 15_000, "producible": True},
        {"key": "uh60",           "name": "UH-60 Black Hawk",     "category": "Aircraft",     "price": 3_000_000,  "initial": 2000, "maint": 8_000,  "producible": True},
        {"key": "ch47",           "name": "CH-47 Chinook",        "category": "Aircraft",     "price": 6_000_000,  "initial": 500,  "maint": 15_000, "producible": True},
        {"key": "ah1z",           "name": "AH-1Z Viper",          "category": "Aircraft",     "price": 4_000_000,  "initial": 100,  "maint": 10_000, "producible": True},
        {"key": "v22",            "name": "V-22 Osprey",          "category": "Aircraft",     "price": 10_000_000, "initial": 400,  "maint": 25_000, "producible": True},
        {"key": "mh60",           "name": "MH-60 Seahawk",        "category": "Aircraft",     "price": 4_000_000,  "initial": 500,  "maint": 10_000, "producible": True},
        # پهپادها
        {"key": "mq9",            "name": "MQ-9 Reaper UAV",      "category": "UAV",          "price": 3_000_000,  "initial": 300,  "maint": 10_000, "producible": True},
        {"key": "rq4",            "name": "RQ-4 Global Hawk UAV", "category": "UAV",          "price": 15_000_000, "initial": 30,   "maint": 30_000, "producible": True},
        {"key": "mq1c",           "name": "MQ-1C Gray Eagle UAV", "category": "UAV",          "price": 2_000_000,  "initial": 100,  "maint": 5_000,  "producible": True},
        {"key": "tactical_drones","name": "Tactical Recon UAVs",  "category": "UAV",          "price": 500_000,    "initial": 300,  "maint": 1_000,  "producible": True},
        # نیروی زمینی
        {"key": "m1a2_abrams",    "name": "M1A2 Abrams Tank",     "category": "Ground Forces","price": 3_000_000,  "initial": 2500, "maint": 8_000,  "producible": True},
        {"key": "m1a1_abrams",    "name": "M1A1 Abrams Tank",     "category": "Ground Forces","price": 2_000_000,  "initial": 1000, "maint": 5_000,  "producible": True},
        {"key": "m2_bradley",     "name": "M2 Bradley IFV",       "category": "Ground Forces","price": 1_200_000,  "initial": 2500, "maint": 3_000,  "producible": True},
        {"key": "stryker",        "name": "Stryker APC",          "category": "Ground Forces","price": 800_000,    "initial": 5000, "maint": 2_000,  "producible": True},
        {"key": "m113_usa",       "name": "M113 APC",             "category": "Ground Forces","price": 300_000,    "initial": 1500, "maint": 800,    "producible": True},
        {"key": "jltv",           "name": "JLTV Tactical Vehicle","category": "Ground Forces","price": 400_000,    "initial": 10000,"maint": 1_000,  "producible": True},
        {"key": "light_armored",  "name": "Light Armored Vehicles","category": "Ground Forces","price": 500_000,   "initial": 6000, "maint": 1_200,  "producible": True},
        # توپخانه
        {"key": "m109_paladin",   "name": "M109 Paladin Howitzer","category": "Artillery",    "price": 1_500_000,  "initial": 900,  "maint": 4_000,  "producible": True},
        {"key": "m777",           "name": "M777 Howitzer",        "category": "Artillery",    "price": 800_000,    "initial": 800,  "maint": 2_000,  "producible": True},
        {"key": "himars",         "name": "HIMARS Rocket System", "category": "Artillery",    "price": 3_000_000,  "initial": 500,  "maint": 8_000,  "producible": True},
        {"key": "m270_mlrs",      "name": "M270 MLRS System",     "category": "Artillery",    "price": 2_500_000,  "initial": 300,  "maint": 6_000,  "producible": True},
        # نیروی دریایی
        {"key": "ford_class",     "name": "Ford Class Carrier",   "category": "Navy",         "price": 100_000_000,"initial": 3,    "maint": 500_000,"producible": True},
        {"key": "nimitz_class",   "name": "Nimitz Class Carrier", "category": "Navy",         "price": 80_000_000, "initial": 10,   "maint": 400_000,"producible": True},
        {"key": "america_class",  "name": "America Class Ship",   "category": "Navy",         "price": 30_000_000, "initial": 2,    "maint": 120_000,"producible": True},
        {"key": "wasp_class",     "name": "Wasp Class Ship",      "category": "Navy",         "price": 25_000_000, "initial": 8,    "maint": 100_000,"producible": True},
        {"key": "san_antonio",    "name": "San Antonio Class",    "category": "Navy",         "price": 15_000_000, "initial": 12,   "maint": 60_000, "producible": True},
        {"key": "harpers_ferry",  "name": "Harpers Ferry Class",  "category": "Navy",         "price": 10_000_000, "initial": 4,    "maint": 40_000, "producible": True},
        {"key": "whidbey_island", "name": "Whidbey Island Class", "category": "Navy",         "price": 10_000_000, "initial": 6,    "maint": 40_000, "producible": True},
        {"key": "burke_class",    "name": "Arleigh Burke Destroyer","category": "Navy",       "price": 20_000_000, "initial": 70,   "maint": 100_000,"producible": True},
        {"key": "zumwalt",        "name": "Zumwalt Destroyer",    "category": "Navy",         "price": 40_000_000, "initial": 3,    "maint": 180_000,"producible": True},
        {"key": "ticonderoga",    "name": "Ticonderoga Cruiser",  "category": "Navy",         "price": 25_000_000, "initial": 10,   "maint": 120_000,"producible": True},
        {"key": "lcs_ship",       "name": "Littoral Combat Ship", "category": "Navy",         "price": 8_000_000,  "initial": 20,   "maint": 30_000, "producible": True},
        {"key": "patrol_coastal", "name": "Patrol / Coastal Ships","category": "Navy",        "price": 1_000_000,  "initial": 70,   "maint": 3_000,  "producible": True},
        {"key": "supply_ships",   "name": "Supply Support Ships", "category": "Navy",         "price": 5_000_000,  "initial": 6,    "maint": 20_000, "producible": True},
        {"key": "puller_ships",   "name": "Lewis B. Puller Base", "category": "Navy",         "price": 8_000_000,  "initial": 2,    "maint": 30_000, "producible": True},
        {"key": "logistics_ships","name": "Logistics & Support Fleet","category":"Navy",     "price": 3_000_000,  "initial": 100,  "maint": 10_000, "producible": True},
        {"key": "virginia_class", "name": "Virginia Class Sub",   "category": "Navy",         "price": 35_000_000, "initial": 25,   "maint": 150_000,"producible": True},
        {"key": "los_angeles_sub","name": "Los Angeles Class Sub","category": "Navy",         "price": 20_000_000, "initial": 20,   "maint": 90_000, "producible": True},
        {"key": "seawolf_sub",    "name": "Seawolf Class Sub",    "category": "Navy",         "price": 45_000_000, "initial": 3,    "maint": 200_000,"producible": True},
        {"key": "ohio_ssbn",      "name": "Ohio Class SSBN Sub",  "category": "Navy",         "price": 50_000_000, "initial": 14,   "maint": 220_000,"producible": True},
        {"key": "ohio_ssgn",      "name": "Ohio Class SSGN Sub",  "category": "Navy",         "price": 40_000_000, "initial": 4,    "maint": 180_000,"producible": True},
        # توان موشکی
        {"key": "tomahawk",       "name": "Tomahawk Cruise Missile","category": "Missiles",   "price": 2_000_000,  "initial": 2000, "maint": 2_000,  "producible": True},
        {"key": "sm6",            "name": "SM-6 Missile",         "category": "Missiles",     "price": 3_000_000,  "initial": 500,  "maint": 4_000,  "producible": True},
        {"key": "sm3",            "name": "SM-3 Anti-Ballistic",  "category": "Missiles",     "price": 10_000_000, "initial": 300,  "maint": 15_000, "producible": True},
        {"key": "aim120",         "name": "AIM-120 AMRAAM",       "category": "Missiles",     "price": 1_000_000,  "initial": 1500, "maint": 1_000,  "producible": True},
        {"key": "aim9x",          "name": "AIM-9X Sidewinder",    "category": "Missiles",     "price": 500_000,    "initial": 1000, "maint": 500,    "producible": True},
        {"key": "jassm",          "name": "AGM-158 JASSM",        "category": "Missiles",     "price": 1_500_000,  "initial": 500,  "maint": 2_000,  "producible": True},
        {"key": "lrasm",          "name": "AGM-158C LRASM",       "category": "Missiles",     "price": 3_000_000,  "initial": 300,  "maint": 4_000,  "producible": True},
        {"key": "harm_aargm",     "name": "AGM-88 HARM/AARGM",    "category": "Missiles",     "price": 1_000_000,  "initial": 500,  "maint": 1_200,  "producible": True},
        {"key": "hellfire",       "name": "AGM-114 Hellfire",     "category": "Missiles",     "price": 150_000,    "initial": 3000, "maint": 200,    "producible": True},
        # پدافند هوایی
        {"key": "patriot_pac3",   "name": "Patriot PAC-3",        "category": "Air Defense",  "price": 10_000_000, "initial": 60,   "maint": 30_000, "producible": True},
        {"key": "thaad",          "name": "THAAD Battery",        "category": "Air Defense",  "price": 40_000_000, "initial": 10,   "maint": 100_000,"producible": True},
        {"key": "nasams",         "name": "NASAMS System",        "category": "Air Defense",  "price": 8_000_000,  "initial": 15,   "maint": 25_000, "producible": True},
        {"key": "avenger",        "name": "Avenger Air Defense",  "category": "Air Defense",  "price": 2_000_000,  "initial": 100,  "maint": 5_000,  "producible": True},
        {"key": "military_radars","name": "Military Radars",      "category": "Air Defense",  "price": 5_000_000,  "initial": 250,  "maint": 15_000, "producible": True},
    ],

    # 🇨🇳 چین (CHINA)
    "china": [
        # تولید بومی (producible=True)
        {"key": "j20",             "name": "J-20 Stealth Fighter", "category": "Aircraft",     "price": 25_000_000, "initial": 250,  "maint": 70_000,"producible": True},
        {"key": "j16",             "name": "J-16 Multirole",       "category": "Aircraft",     "price": 15_000_000, "initial": 350,  "maint": 40_000,"producible": True},
        {"key": "j10c",            "name": "J-10C Fighter",        "category": "Aircraft",     "price": 10_000_000, "initial": 500,  "maint": 25_000,"producible": True},
        {"key": "j11",             "name": "J-11 Fighter",         "category": "Aircraft",     "price": 12_000_000, "initial": 200,  "maint": 30_000,"producible": True},
        {"key": "j15",             "name": "J-15 Flying Shark",    "category": "Aircraft",     "price": 15_000_000, "initial": 100,  "maint": 35_000,"producible": True},
        {"key": "jh7",             "name": "JH-7 Flounder",        "category": "Aircraft",     "price": 8_000_000,  "initial": 100,  "maint": 20_000,"producible": True},
        {"key": "h6k",             "name": "H-6K / H-6N Bomber",   "category": "Aircraft",     "price": 30_000_000, "initial": 120,  "maint": 80_000,"producible": True},
        {"key": "y20",             "name": "Y-20 Transporter",     "category": "Aircraft",     "price": 25_000_000, "initial": 80,   "maint": 50_000,"producible": True},
        {"key": "y9",              "name": "Y-9 Transport",        "category": "Aircraft",     "price": 10_000_000, "initial": 100,  "maint": 20_000,"producible": True},
        {"key": "yy20_tanker",     "name": "YY-20 Aerial Tanker",  "category": "Aircraft",     "price": 25_000_000, "initial": 30,   "maint": 50_000,"producible": True},
        {"key": "kj500",           "name": "KJ-500 AWACS",         "category": "Aircraft",     "price": 20_000_000, "initial": 50,   "maint": 45_000,"producible": True},
        {"key": "kj200",           "name": "KJ-200 AWACS",         "category": "Aircraft",     "price": 15_000_000, "initial": 20,   "maint": 30_000,"producible": True},
        {"key": "y8_y9_recon",     "name": "Y-8/Y-9 Reconnaissance","category": "Aircraft",    "price": 12_000_000, "initial": 40,   "maint": 25_000,"producible": True},
        {"key": "gj11",            "name": "GJ-11 Stealth UAV",    "category": "UAV",          "price": 5_000_000,  "initial": 30,   "maint": 12_000,"producible": True},
        {"key": "wing_loong2",     "name": "Wing Loong II",        "category": "UAV",          "price": 2_000_000,  "initial": 100,  "maint": 5_000, "producible": True},
        {"key": "ch4_uav",         "name": "CH-4 UAV",             "category": "UAV",          "price": 1_500_000,  "initial": 80,   "maint": 3_500, "producible": True},
        {"key": "tactical_drones_c","name": "Tactical Recon UAVs", "category": "UAV",          "price": 300_000,    "initial": 500,  "maint": 800,   "producible": True},
        {"key": "z10_heli",        "name": "Z-10 Attack Heli",     "category": "Aircraft",     "price": 5_000_000,  "initial": 150,  "maint": 12_000,"producible": True},
        {"key": "z19_heli",        "name": "Z-19 Recon Heli",      "category": "Aircraft",     "price": 3_000_000,  "initial": 100,  "maint": 8_000, "producible": True},
        {"key": "z20_heli",        "name": "Z-20 Transport Heli",  "category": "Aircraft",     "price": 4_000_000,  "initial": 150,  "maint": 10_000,"producible": True},
        {"key": "z8_z18_heli",     "name": "Z-8 / Z-18 Heli",      "category": "Aircraft",     "price": 5_000_000,  "initial": 150,  "maint": 12_000,"producible": True},
        {"key": "type_99a",        "name": "Type 99A Tank",        "category": "Ground Forces","price": 3_500_000,  "initial": 1200, "maint": 8_000, "producible": True},
        {"key": "type_96ab",       "name": "Type 96A/B Tank",      "category": "Ground Forces","price": 2_000_000,  "initial": 2500, "maint": 4_500, "producible": True},
        {"key": "type_15",         "name": "Type 15 Light Tank",   "category": "Ground Forces","price": 1_800_000,  "initial": 800,  "maint": 4_000, "producible": True},
        {"key": "zbd_04a",         "name": "ZBD-04A IFV",          "category": "Ground Forces","price": 1_200_000,  "initial": 1000, "maint": 3_000, "producible": True},
        {"key": "zbl_08",          "name": "ZBL-08 Wheeled IFV",   "category": "Ground Forces","price": 1_000_000,  "initial": 2000, "maint": 2_500, "producible": True},
        {"key": "zbd_05",          "name": "ZBD-05 Amphibious IFV","category": "Ground Forces","price": 1_500_000,  "initial": 600,  "maint": 3_500, "producible": True},
        {"key": "light_armored_c", "name": "Light Armored Vehicles","category": "Ground Forces","price": 300_000,   "initial": 6000, "maint": 800,   "producible": True},
        {"key": "plz_05",          "name": "PLZ-05 Howitzer",      "category": "Artillery",    "price": 1_800_000,  "initial": 400,  "maint": 4_000, "producible": True},
        {"key": "pcl_181",         "name": "PCL-181 Wheeled Howitzer","category": "Artillery", "price": 1_200_000,  "initial": 500,  "maint": 3_000, "producible": True},
        {"key": "phl_16",          "name": "PHL-16 Heavy MLRS",    "category": "Artillery",    "price": 3_500_000,  "initial": 300,  "maint": 8_000, "producible": True},
        {"key": "phl_03",          "name": "PHL-03 MLRS",          "category": "Artillery",    "price": 2_000_000,  "initial": 200,  "maint": 5_000, "producible": True},
        {"key": "sr5_mlrs",        "name": "SR-5 Modular MLRS",    "category": "Artillery",    "price": 1_500_000,  "initial": 150,  "maint": 3_500, "producible": True},
        {"key": "fujian_carrier",  "name": "Fujian Class Carrier", "category": "Navy",         "price": 100_000_000,"initial": 1,    "maint": 500_000,"producible": True},
        {"key": "shandong_carrier","name": "Shandong Class Carrier","category": "Navy",        "price": 80_000_000, "initial": 1,    "maint": 400_000,"producible": True},
        {"key": "liaoning_carrier","name": "Liaoning Class Carrier","category": "Navy",        "price": 70_000_000, "initial": 1,    "maint": 350_000,"producible": True},
        {"key": "type_055",        "name": "Type 055 Stealth Destroyer","category": "Navy",   "price": 30_000_000, "initial": 8,    "maint": 120_000,"producible": True},
        {"key": "type_052d",       "name": "Type 052D Destroyer",  "category": "Navy",         "price": 20_000_000, "initial": 30,   "maint": 80_000, "producible": True},
        {"key": "type_052c",       "name": "Type 052C Destroyer",  "category": "Navy",         "price": 15_000_000, "initial": 6,    "maint": 60_000, "producible": True},
        {"key": "type_054a",       "name": "Type 054A Frigate",    "category": "Navy",         "price": 10_000_000, "initial": 30,   "maint": 40_000, "producible": True},
        {"key": "patrol_combat_c", "name": "Patrol / Coastal Ships","category": "Navy",        "price": 800_000,    "initial": 100,  "maint": 2_000, "producible": True},
        {"key": "type_075",        "name": "Type 075 LHD Ship",    "category": "Navy",         "price": 35_000_000, "initial": 3,    "maint": 120_000,"producible": True},
        {"key": "type_071",        "name": "Type 071 LPD Ship",    "category": "Navy",         "price": 20_000_000, "initial": 8,    "maint": 70_000, "producible": True},
        {"key": "type_093_sub",    "name": "Type 093 Attack Sub",  "category": "Navy",         "price": 30_000_000, "initial": 6,    "maint": 120_000,"producible": True},
        {"key": "type_039ab_sub",  "name": "Type 039A/B Submarine","category": "Navy",        "price": 12_000_000, "initial": 20,   "maint": 45_000, "producible": True},
        {"key": "type_039_sub",    "name": "Type 039 Submarine",   "category": "Navy",         "price": 8_000_000,  "initial": 10,   "maint": 30_000, "producible": True},
        {"key": "type_094_ssbn",   "name": "Type 094 SSBN Sub",    "category": "Navy",         "price": 45_000_000, "initial": 6,    "maint": 200_000,"producible": True},
        {"key": "df21",            "name": "DF-21 Anti-Ship",      "category": "Missiles",     "price": 5_000_000,  "initial": 100,  "maint": 10_000, "producible": True},
        {"key": "df26",            "name": "DF-26 Guam Killer",    "category": "Missiles",     "price": 8_000_000,  "initial": 80,   "maint": 15_000, "producible": True},
        {"key": "df17",            "name": "DF-17 Hypersonic",     "category": "Missiles",     "price": 10_000_000, "initial": 50,   "maint": 20_000, "producible": True},
        {"key": "df41",            "name": "DF-41 ICBM",           "category": "Missiles",     "price": 20_000_000, "initial": 40,   "maint": 50_000, "producible": True},
        {"key": "cj10",            "name": "CJ-10 Cruise Missile", "category": "Missiles",     "price": 2_000_000,  "initial": 300,  "maint": 3_000,  "producible": True},
        {"key": "yj12",            "name": "YJ-12 Anti-Ship",      "category": "Missiles",     "price": 2_500_000,  "initial": 200,  "maint": 4_000,  "producible": True},
        {"key": "yj18",            "name": "YJ-18 Anti-Ship",      "category": "Missiles",     "price": 3_000_000,  "initial": 300,  "maint": 5_000,  "producible": True},
        {"key": "pl15",            "name": "PL-15 Air-to-Air",     "category": "Missiles",     "price": 1_000_000,  "initial": 800,  "maint": 1_500,  "producible": True},
        {"key": "pl10",            "name": "PL-10 Air-to-Air",     "category": "Missiles",     "price": 500_000,    "initial": 600,  "maint": 800,    "producible": True},
        {"key": "hq9_hq9b",        "name": "HQ-9 / HQ-9B",         "category": "Air Defense",  "price": 12_000_000, "initial": 40,   "maint": 35_000, "producible": True},
        {"key": "hq22",            "name": "HQ-22 Air Defense",    "category": "Air Defense",  "price": 8_000_000,  "initial": 30,   "maint": 25_000, "producible": True},
        {"key": "hq16",            "name": "HQ-16 Medium Range",   "category": "Air Defense",  "price": 5_000_000,  "initial": 40,   "maint": 15_000, "producible": True},
        {"key": "hq17",            "name": "HQ-17 Short Range",    "category": "Air Defense",  "price": 4_000_000,  "initial": 30,   "maint": 12_000, "producible": True},
        {"key": "ld2000",          "name": "LD-2000 SPAAG/CIWS",   "category": "Air Defense",  "price": 1_500_000,  "initial": 100,  "maint": 4_000,  "producible": True},
        {"key": "radars_china",    "name": "Military Radar Systems","category": "Air Defense", "price": 4_000_000,  "initial": 250,  "maint": 12_000, "producible": True},

        # وارداتی (producible=False)
        {"key": "il76_china",      "name": "Il-76 Transporter (وارداتی)","category":"Aircraft","price":15_000_000,  "initial": 20,   "maint": 35_000, "producible": False},
        {"key": "mi17_china",      "name": "Mi-17 Helicopter (وارداتی)","category":"Aircraft", "price": 3_000_000,  "initial": 100,  "maint": 8_000,  "producible": False},
    ],

    # 🇷🇺 روسیه (RUSSIA)
    "russia": [
        # تولید بومی (producible=True)
        {"key": "su57",           "name": "Su-57 Felon",          "category": "Aircraft",     "price": 20_000_000, "initial": 24,   "maint": 70_000,"producible": True},
        {"key": "su35",           "name": "Su-35S Flanker-E",     "category": "Aircraft",     "price": 12_000_000, "initial": 100,  "maint": 40_000,"producible": True},
        {"key": "su30sm",         "name": "Su-30SM",              "category": "Aircraft",     "price": 11_000_000, "initial": 130,  "maint": 35_000,"producible": True},
        {"key": "mig35",          "name": "MiG-35",               "category": "Aircraft",     "price": 9_000_000,  "initial": 30,   "maint": 25_000,"producible": True},
        {"key": "mig29_russia",   "name": "MiG-29",               "category": "Aircraft",     "price": 7_000_000,  "initial": 200,  "maint": 20_000,"producible": True},
        {"key": "su27",           "name": "Su-27 Flanker",        "category": "Aircraft",     "price": 8_000_000,  "initial": 100,  "maint": 22_000,"producible": True},
        {"key": "tu160",          "name": "Tu-160 Blackjack Bomber","category": "Aircraft",   "price": 40_000_000, "initial": 16,   "maint": 120_000,"producible": True},
        {"key": "tu95ms",         "name": "Tu-95MS Bear Bomber",  "category": "Aircraft",     "price": 25_000_000, "initial": 60,   "maint": 80_000,"producible": True},
        {"key": "tu22m3",         "name": "Tu-22M3 Backfire Bomber","category": "Aircraft",   "price": 20_000_000, "initial": 60,   "maint": 70_000,"producible": True},
        {"key": "il76_russia",    "name": "Il-76 Transporter",    "category": "Aircraft",     "price": 15_000_000, "initial": 120,  "maint": 35_000,"producible": True},
        {"key": "il78_tanker",    "name": "Il-78 Aerial Tanker",  "category": "Aircraft",     "price": 18_000_000, "initial": 20,   "maint": 40_000,"producible": True},
        {"key": "a50_awacs",      "name": "A-50 Mainstay AWACS",  "category": "Aircraft",     "price": 20_000_000, "initial": 15,   "maint": 45_000,"producible": True},
        {"key": "orion_uav",      "name": "Orion Recon UAV",      "category": "UAV",          "price": 1_500_000,  "initial": 50,   "maint": 4_000, "producible": True},
        {"key": "forpost_uav",    "name": "Forpost UAV",          "category": "UAV",          "price": 1_000_000,  "initial": 100,  "maint": 3_000, "producible": True},
        {"key": "geran2_drone",   "name": "Geran-2 Drone",        "category": "UAV",          "price": 100_000,    "initial": 500,  "maint": 500,   "producible": True},
        {"key": "tactical_drones_r","name": "Tactical Recon UAVs","category": "UAV",          "price": 300_000,    "initial": 500,  "maint": 800,   "producible": True},
        {"key": "ka52_heli",      "name": "Ka-52 Alligator",      "category": "Aircraft",     "price": 6_000_000,  "initial": 150,  "maint": 15_000,"producible": True},
        {"key": "mi28_heli",      "name": "Mi-28 Havoc",          "category": "Aircraft",     "price": 5_000_000,  "initial": 100,  "maint": 12_000,"producible": True},
        {"key": "mi8_mi17_russia","name": "Mi-8 / Mi-17",         "category": "Aircraft",     "price": 3_000_000,  "initial": 500,  "maint": 8_000, "producible": True},
        {"key": "mi26_heli",      "name": "Mi-26 Heavy Transport","category": "Aircraft",     "price": 8_000_000,  "initial": 30,   "maint": 20_000,"producible": True},
        {"key": "t90m",           "name": "T-90M Proryv Tank",    "category": "Ground Forces","price": 2_500_000,  "initial": 800,  "maint": 6_000, "producible": True},
        {"key": "t72b3",          "name": "T-72B3 Tank",          "category": "Ground Forces","price": 1_500_000,  "initial": 3000, "maint": 4_000, "producible": True},
        {"key": "t80bvm",         "name": "T-80BVM Tank",         "category": "Ground Forces","price": 2_000_000,  "initial": 1000, "maint": 5_000, "producible": True},
        {"key": "t14_armata",     "name": "T-14 Armata Tank",     "category": "Ground Forces","price": 5_000_000,  "initial": 100,  "maint": 12_000,"producible": True},
        {"key": "bmp3_ifv",       "name": "BMP-3 IFV",            "category": "Ground Forces","price": 1_200_000,  "initial": 2000, "maint": 3_000, "producible": True},
        {"key": "bmp2_ifv",       "name": "BMP-2 IFV",            "category": "Ground Forces","price": 800_000,    "initial": 3000, "maint": 2_000, "producible": True},
        {"key": "btr82a",         "name": "BTR-82A APC",          "category": "Ground Forces","price": 600_000,    "initial": 1500, "maint": 1_500, "producible": True},
        {"key": "light_armored_r","name": "Light Armored Vehicles","category": "Ground Forces","price": 300_000,   "initial": 5000, "maint": 800,   "producible": True},
        {"key": "msta_s",          "name": "2S19 Msta-S Howitzer", "category": "Artillery",    "price": 1_800_000,  "initial": 800,  "maint": 4_000, "producible": True},
        {"key": "towed_artillery_r","name": "Towed Artillery",     "category": "Artillery",    "price": 300_000,    "initial": 2000, "maint": 800,   "producible": True},
        {"key": "bm21_grad_r",    "name": "BM-21 Grad MLRS",      "category": "Artillery",    "price": 500_000,    "initial": 2000, "maint": 1_200, "producible": True},
        {"key": "bm30_smerch",    "name": "BM-30 Smerch MLRS",    "category": "Artillery",    "price": 2_500_000,  "initial": 300,  "maint": 6_000, "producible": True},
        {"key": "iskander_system","name": "9K720 Iskander System","category": "Artillery",    "price": 3_000_000,  "initial": 150,  "maint": 8_000, "producible": True},
        {"key": "admiral_gorshkov","name": "Admiral Gorshkov Frigate","category": "Navy",     "price": 20_000_000, "initial": 4,    "maint": 70_000, "producible": True},
        {"key": "admiral_grigorovich","name": "Admiral Grigorovich Frigate","category": "Navy","price": 15_000_000, "initial": 6,   "maint": 50_000, "producible": True},
        {"key": "kirov_cruiser",  "name": "Kirov Class Cruiser",  "category": "Navy",         "price": 60_000_000, "initial": 1,    "maint": 250_000,"producible": True},
        {"key": "borei",          "name": "Borei Class Submarine","category": "Navy",         "price": 40_000_000, "initial": 6,    "maint": 200_000,"producible": True},
        {"key": "yasen_sub",      "name": "Yasen Class Submarine","category": "Navy",         "price": 35_000_000, "initial": 4,    "maint": 180_000,"producible": True},
        {"key": "akula_sub",      "name": "Akula Class Submarine","category": "Navy",         "price": 25_000_000, "initial": 10,   "maint": 100_000,"producible": True},
        {"key": "kilo_russia",    "name": "Kilo Class Submarine", "category": "Navy",         "price": 15_000_000, "initial": 20,   "maint": 50_000, "producible": True},
        {"key": "corvettes_russia","name": "Frigates & Corvettes", "category": "Navy",        "price": 10_000_000, "initial": 70,   "maint": 30_000, "producible": True},
        {"key": "patrol_ships_r", "name": "Patrol Ships",         "category": "Navy",         "price": 1_000_000,  "initial": 200,  "maint": 3_000,  "producible": True},
        {"key": "iskander_m_m",   "name": "Iskander-M Missile",   "category": "Missiles",     "price": 3_000_000,  "initial": 150,  "maint": 5_000,  "producible": True},
        {"key": "kalibr",         "name": "Kalibr Cruise Missile","category": "Missiles",     "price": 1_500_000,  "initial": 2000, "maint": 1_500,  "producible": True},
        {"key": "kinzhal_hypersonic","name": "Kinzhal Hypersonic", "category": "Missiles",     "price": 5_000_000,  "initial": 100,  "maint": 10_000, "producible": True},
        {"key": "zircon_hypersonic","name": "Zircon Hypersonic",   "category": "Missiles",     "price": 6_000_000,  "initial": 50,   "maint": 12_000, "producible": True},
        {"key": "kh101_cruise",   "name": "Kh-101 Cruise Missile","category": "Missiles",     "price": 2_000_000,  "initial": 500,  "maint": 3_000,  "producible": True},
        {"key": "antiship_russia","name": "Anti-Ship Missiles",   "category": "Missiles",     "price": 1_000_000,  "initial": 1000, "maint": 1_500,  "producible": True},
        {"key": "s400",           "name": "S-400 Triumf System",  "category": "Air Defense",  "price": 15_000_000, "initial": 50,   "maint": 40_000, "producible": True},
        {"key": "s300_russia",    "name": "S-300 System",         "category": "Air Defense",  "price": 10_000_000, "initial": 100,  "maint": 25_000, "producible": True},
        {"key": "s350_vityaz",    "name": "S-350 Vityaz",         "category": "Air Defense",  "price": 8_000_000,  "initial": 20,   "maint": 20_000, "producible": True},
        {"key": "pantsir",        "name": "Pantsir-S1 System",    "category": "Air Defense",  "price": 5_000_000,  "initial": 100,  "maint": 15_000, "producible": True},
        {"key": "tor_m2",         "name": "Tor-M2",               "category": "Air Defense",  "price": 6_000_000,  "initial": 150,  "maint": 18_000, "producible": True},
        {"key": "buk_m3",         "name": "Buk-M3",               "category": "Air Defense",  "price": 7_000_000,  "initial": 70,   "maint": 20_000, "producible": True},
        {"key": "radars_russia",  "name": "Military Radar Systems","category": "Air Defense", "price": 4_000_000,  "initial": 300,  "maint": 12_000, "producible": True},
    ],

    # 🇬🇧 پادشاهی متحد بریتانیا (UK)
    "uk": [
        # بومی (producible=True)
        {"key": "typhoon_uk",      "name": "Eurofighter Typhoon",  "category": "Aircraft",     "price": 18_000_000, "initial": 140,  "maint": 50_000, "producible": True},
        {"key": "strike_aircraft_uk","name":"Strike Aircraft Fleet","category": "Aircraft",  "price": 15_000_000, "initial": 100,  "maint": 40_000, "producible": True},
        {"key": "challenger2",     "name": "Challenger 2 Tank",    "category": "Ground Forces","price": 3_500_000,  "initial": 220,  "maint": 8_000,  "producible": True},
        {"key": "challenger3",     "name": "Challenger 3 Tank",    "category": "Ground Forces","price": 5_000_000,  "initial": 14,   "maint": 12_000, "producible": True},
        {"key": "ajax_armored",    "name": "Ajax Armored Vehicle", "category": "Ground Forces","price": 2_000_000,  "initial": 100,  "maint": 5_000,  "producible": True},
        {"key": "warrior_ifv",     "name": "Warrior IFV",          "category": "Ground Forces","price": 1_000_000,  "initial": 300,  "maint": 2_500,  "producible": True},
        {"key": "boxer_uk",        "name": "Boxer Armored Vehicle","category": "Ground Forces","price": 1_500_000,  "initial": 200,  "maint": 3_500,  "producible": True},
        {"key": "jackal_vehicle",  "name": "Jackal High Mobility", "category": "Ground Forces","price": 500_000,    "initial": 500,  "maint": 1_200,  "producible": True},
        {"key": "light_armored_uk","name": "Light Armored Vehicles","category": "Ground Forces","price": 400_000,  "initial": 1500, "maint": 1_000,  "producible": True},
        {"key": "as90_howitzer",   "name": "AS90 Howitzer",        "category": "Artillery",    "price": 2_000_000,  "initial": 60,   "maint": 5_000,  "producible": True},
        {"key": "l118_lightgun",   "name": "L118 Light Gun",       "category": "Artillery",    "price": 500_000,    "initial": 100,  "maint": 1_200,  "producible": True},
        {"key": "queen_elizabeth_carrier","name":"Queen Elizabeth Carrier","category":"Navy", "price": 90_000_000, "initial": 2,    "maint": 450_000,"producible": True},
        {"key": "type_45_destroyer","name":"Type 45 Destroyer",    "category": "Navy",         "price": 25_000_000, "initial": 6,    "maint": 100_000,"producible": True},
        {"key": "type_23_frigate", "name": "Type 23 Duke Frigate",  "category": "Navy",         "price": 15_000_000, "initial": 11,   "maint": 50_000, "producible": True},
        {"key": "river_class_patrol","name":"River Class Patrol Ship","category":"Navy",     "price": 2_000_000,  "initial": 8,    "maint": 5_000,  "producible": True},
        {"key": "astute_sub",      "name": "Astute Class Submarine","category": "Navy",        "price": 35_000_000, "initial": 5,    "maint": 150_000,"producible": True},
        {"key": "vanguard_ssbn",   "name": "Vanguard Class SSBN",  "category": "Navy",         "price": 50_000_000, "initial": 4,    "maint": 220_000,"producible": True},
        {"key": "storm_shadow",    "name": "Storm Shadow Cruise",  "category": "Missiles",     "price": 2_000_000,  "initial": 300,  "maint": 3_000,  "producible": True},
        {"key": "spear_missile",   "name": "Spear 3 Missile",      "category": "Missiles",     "price": 800_000,    "initial": 500,  "maint": 1_200,  "producible": True},
        {"key": "meteor_uk",       "name": "Meteor BVR Missile",   "category": "Missiles",     "price": 1_500_000,  "initial": 300,  "maint": 2_000,  "producible": True},
        {"key": "asraam_missile",  "name": "ASRAAM Air-to-Air",    "category": "Missiles",     "price": 500_000,    "initial": 400,  "maint": 800,    "producible": True},
        {"key": "brimstone_missile","name":"Brimstone Precision",  "category": "Missiles",     "price": 300_000,    "initial": 1000, "maint": 500,    "producible": True},
        {"key": "sea_viper",       "name": "Sea Viper Defense",    "category": "Missiles",     "price": 2_000_000,  "initial": 300,  "maint": 3_000,  "producible": True},
        {"key": "antiship_uk",     "name": "Anti-Ship Missiles",   "category": "Missiles",     "price": 1_000_000,  "initial": 300,  "maint": 1_500,  "producible": True},
        {"key": "sky_sabre",       "name": "Sky Sabre Air Defense","category": "Air Defense",  "price": 8_000_000,  "initial": 12,   "maint": 25_000, "producible": True},
        {"key": "starstreak",      "name": "Starstreak System",    "category": "Air Defense",  "price": 1_000_000,  "initial": 100,  "maint": 2_500,  "producible": True},
        {"key": "stormer_hvm",     "name": "Stormer HVM Vehicle",  "category": "Air Defense",  "price": 1_500_000,  "initial": 60,   "maint": 3_500,  "producible": True},

        # وارداتی (producible=False)
        {"key": "f35b_uk",         "name": "F-35B (وارداتی)",      "category": "Aircraft",     "price": 16_000_000, "initial": 70,   "maint": 55_000, "producible": False},
        {"key": "f15_uk",          "name": "F-15 Eagle (وارداتی)", "category": "Aircraft",     "price": 12_000_000, "initial": 30,   "maint": 35_000, "producible": False},
        {"key": "f16_uk",          "name": "F-16 Falcon (وارداتی)","category": "Aircraft",     "price": 8_000_000,  "initial": 20,   "maint": 20_000, "producible": False},
        {"key": "a400m_uk",        "name": "A400M Atlas (وارداتی)","category": "Aircraft",     "price": 20_000_000, "initial": 25,   "maint": 40_000, "producible": False},
        {"key": "c17_uk",          "name": "C-17 (وارداتی)",       "category": "Aircraft",     "price": 20_000_000, "initial": 8,    "maint": 45_000, "producible": False},
        {"key": "c130j_uk",        "name": "C-130J (وارداتی)",     "category": "Aircraft",     "price": 8_000_000,  "initial": 14,   "maint": 18_000, "producible": False},
        {"key": "voyager_kc",      "name": "Voyager Tanker (وارداتی)","category":"Aircraft",   "price": 25_000_000, "initial": 10,   "maint": 50_000, "producible": False},
        {"key": "e7_wedgetail_uk", "name": "E-7 Wedgetail (وارداتی)","category":"Aircraft",    "price": 30_000_000, "initial": 5,    "maint": 60_000, "producible": False},
        {"key": "rc135w_uk",       "name": "RC-135W (وارداتی)",    "category": "Aircraft",     "price": 20_000_000, "initial": 3,    "maint": 40_000, "producible": False},
        {"key": "protector_rg",    "name": "Protector RG Mk1 (وارداتی)","category":"UAV",      "price": 3_000_000,  "initial": 16,   "maint": 8_000,  "producible": False},
        {"key": "watchkeeper",     "name": "Watchkeeper WK450 (وارداتی)","category":"UAV",     "price": 1_000_000,  "initial": 50,   "maint": 3_000,  "producible": False},
        {"key": "tactical_drones_uk","name":"پهپادهای تاکتیکی",     "category": "UAV",          "price": 400_000,    "initial": 150,  "maint": 1_000,  "producible": False},
        {"key": "ah64e_uk",        "name": "AH-64E Apache (وارداتی)","category":"Aircraft",    "price": 5_000_000,  "initial": 50,   "maint": 15_000, "producible": False},
        {"key": "merlin_heli",     "name": "Merlin Helicopter",    "category": "Aircraft",     "price": 6_000_000,  "initial": 60,   "maint": 15_000, "producible": False},
        {"key": "wildcat_heli",    "name": "Wildcat Helicopter",   "category": "Aircraft",     "price": 4_000_000,  "initial": 30,   "maint": 10_000, "producible": False},
        {"key": "chinook_uk",      "name": "Chinook (وارداتی)",    "category": "Aircraft",     "price": 6_000_000,  "initial": 60,   "maint": 15_000, "producible": False},
        {"key": "puma_hc2",        "name": "Puma HC2",             "category": "Aircraft",     "price": 3_000_000,  "initial": 20,   "maint": 8_000,  "producible": False},
        {"key": "m270_mlrs_uk",    "name": "M270 MLRS (وارداتی)",  "category": "Artillery",    "price": 2_500_000,  "initial": 40,   "maint": 6_000,  "producible": False},
        {"key": "aim120_uk",       "name": "AIM-120 AMRAAM (وارداتی)","category":"Missiles",   "price": 1_000_000,  "initial": 500,  "maint": 1_000,  "producible": False},
        {"key": "radars_uk",       "name": "رادارهای نظامی",       "category": "Air Defense",  "price": 4_000_000,  "initial": 120,  "maint": 12_000, "producible": False},
    ],
}

# کاتالوگ عمومی برای سایر کشورها
DEFAULT_COUNTRY_EQUIPMENT = [
    {"key": "gen_fighter",   "name": "جنگنده پیشرفته نسل ۴.۵", "category": "Aircraft",     "price": 10_000_000, "initial": 150, "maint": 25_000, "producible": True},
    {"key": "gen_bomber",    "name": "بمب‌افکن استراتژیک",     "category": "Aircraft",     "price": 25_000_000, "initial": 20,  "maint": 60_000, "producible": True},
    {"key": "gen_missile",   "name": "موشک کروز استراتژیک",   "category": "Missiles",     "price": 2_000_000,  "initial": 500, "maint": 2_000,  "producible": True},
    {"key": "gen_airdef",    "name": "سامانه پدافند موشکی",  "category": "Air Defense",  "price": 10_000_000, "initial": 20,  "maint": 25_000, "producible": True},
    {"key": "gen_uav",       "name": "پهپاد شناسایی-رزمی",  "category": "UAV",          "price": 1_000_000,  "initial": 200, "maint": 3_000,  "producible": True},
    {"key": "gen_frigate",   "name": "ناو محافظ سنگین",       "category": "Navy",         "price": 20_000_000, "initial": 10,  "maint": 80_000, "producible": True},
    {"key": "gen_tank",      "name": "تانک اصلی میدان نبرد",  "category": "Ground Forces","price": 2_000_000,  "initial": 1000,"maint": 5_000,  "producible": True},
    {"key": "gen_artillery", "name": "توپخانه خودکششی",       "category": "Artillery",    "price": 1_500_000,  "initial": 300, "maint": 4_000,  "producible": True},
]

# ===== فروشگاه: ساختمان‌ها =====
BUILDINGS = {
    "house":      {"name": "🏠 ساختمان مسکونی", "price": 1_000_000},
    "office":     {"name": "🏢 ساختمان اداری",   "price": 2_000_000},
    "commercial": {"name": "🏬 ساختمان تجاری",   "price": 3_000_000},
    "hotel":      {"name": "🏨 هتل",             "price": 7_000_000},
    "tower":      {"name": "🏙️ برج تجاری",       "price": 10_000_000},
    "skyscraper": {"name": "🏙️ آسمان‌خراش",      "price": 20_000_000},
}

# ===== فروشگاه: صنعت =====
FACTORIES = {
    "small_factory":    {"name": "🏭 کارخانه کوچک",   "price": 3_000_000},
    "medium_factory":   {"name": "🏭 کارخانه متوسط",  "price": 7_000_000},
    "large_factory":    {"name": "🏭 کارخانه بزرگ",   "price": 15_000_000},
    "industrial_complex": {"name": "🏭 مجتمع صنعتی", "price": 25_000_000},
}

# ===== فروشگاه: انرژی =====
POWER_PLANTS = {
    "fossil_plant":  {"name": "⚡ نیروگاه فسیلی",   "price": 10_000_000},
    "solar_plant":   {"name": "☀️ نیروگاه خورشیدی", "price": 8_000_000},
    "wind_plant":    {"name": "🌬️ نیروگاه بادی",    "price": 10_000_000},
    "hydro_plant":   {"name": "💧 نیروگاه آبی",     "price": 15_000_000},
    "nuclear_plant": {"name": "☢️ نیروگاه هسته‌ای", "price": 50_000_000},
}

ALL_SHOP_ITEMS = {}
for group in (BUILDINGS, FACTORIES, POWER_PLANTS):
    ALL_SHOP_ITEMS.update(group)

# ===== مسیر فایل دیتابیس =====
DB_PATH = os.environ.get("DB_PATH", "game.db")
