# -*- coding: utf-8 -*-
"""
تنظیمات عمومی بازی، لیست ۱۷ کشور، مقادیر اولیه و کاتالوگ جامع دارایی‌های نظامی اختصاصی تمام کشورها (Country Assets Catalog).
شامل تفکیک دقیق سلاح‌های تولید بومی (producible=True) از سلاح‌های وارداتی (producible=False).
"""

import os

# ===== توکن بات =====
BOT_TOKEN = os.environ.get("BOT_TOKEN", "TOKEN_ATO_EINJA_BEZAR")

# ===== آیدی عددی ادمین اصلی =====
admin_env = os.environ.get("ADMIN_IDS", "")
if admin_env:
    ADMIN_IDS = [int(x.strip()) for x in admin_env.split(",") if x.strip().isdigit()]
else:
    ADMIN_IDS = [
        8052987465,
    ]

# ===== لیست کامل کشورهای قابل انتخاب در بازی (۱۷ کشور) =====
COUNTRIES = {
    "iran":    {"name": "ایران",    "flag": "🇮🇷"},
    "germany": {"name": "آلمان",    "flag": "🇩🇪"},
    "qatar":   {"name": "قطر",      "flag": "🇶🇦"},
    "usa":     {"name": "آمریکا",   "flag": "🇺🇸"},
    "russia":  {"name": "روسیه",    "flag": "🇷🇺"},
    "china":   {"name": "چین",      "flag": "🇨🇳"},
    "france":  {"name": "فرانسه",   "flag": "🇫🇷"},
    "uk":      {"name": "انگلیس",   "flag": "🇬🇧"},
    "japan":   {"name": "ژاپن",     "flag": "🇯🇵"},
    "turkey":  {"name": "ترکیه",    "flag": "🇹🇷"},
    "saudi":   {"name": "عربستان",  "flag": "🇸🇦"},
    "ukraine": {"name": "اوکراین",  "flag": "🇺🇦"},
    "india":   {"name": "هند",      "flag": "🇮🇳"},
    "brazil":  {"name": "برزیل",    "flag": "🇧🇷"},
    "egypt":   {"name": "مصر",      "flag": "🇪🇬"},
    "uae":     {"name": "امارات",   "flag": "🇦🇪"},
    "israel":  {"name": "اسرائیل",  "flag": "🇮🇱"},
}

# ===== مقادیر اولیه عمومی کشورها =====
STARTING_VALUES = {
    "population": 20_000_000,
    "treasury": 40_000_000,
    "tax_income": 8_000_000,
    "daily_income": 15_000_000,
    "gold": 300,
    "gold_daily": 40,
    "oil_reserves": 100_000_000,
    "oil_production": 1_500_000,
    "grain": 100,
    "electricity": 130,
    "active_personnel": 200_000,
    "reserve_personnel": 500_000,
}

# ===== مقادیر اختصاصی و دقیق اقتصادی و انسانی تمام کشورها =====
COUNTRY_STARTING_OVERRIDES = {
    "france": {
        "population": 68_000_000,
        "treasury": 60_000_000,
        "tax_income": 10_000_000,
        "daily_income": 18_000_000,
        "gold": 350,
        "gold_daily": 50,
        "oil_reserves": 20_000_000,
        "oil_production": 500_000,
        "grain": 45,
        "electricity": 150,
        "active_personnel": 200_000,
        "reserve_personnel": 700_000,
    },
    "ukraine": {
        "population": 38_000_000,
        "treasury": 25_000_000,
        "tax_income": 4_000_000,
        "daily_income": 8_000_000,
        "gold": 150,
        "gold_daily": 25,
        "oil_reserves": 10_000_000,
        "oil_production": 100_000,
        "grain": 50,
        "electricity": 130,
        "active_personnel": 800_000,
        "reserve_personnel": 900_000,
    },
    "qatar": {
        "population": 3_000_000,
        "treasury": 35_000_000,
        "tax_income": 4_000_000,
        "daily_income": 12_000_000,
        "gold": 200,
        "gold_daily": 40,
        "oil_reserves": 25_000_000,
        "oil_production": 2_500_000,
        "grain": 15,
        "electricity": 140,
        "active_personnel": 12_000,
        "reserve_personnel": 20_000,
    },
    "usa": {
        "population": 340_000_000,
        "treasury": 80_000_000,
        "tax_income": 12_000_000,
        "daily_income": 8_000_000,
        "gold": 500,
        "gold_daily": 60,
        "oil_reserves": 250_000_000,
        "oil_production": 5_000_000,
        "grain": 50,
        "electricity": 145,
        "active_personnel": 1_300_000,
        "reserve_personnel": 800_000,
    },
    "israel": {
        "population": 10_000_000,
        "treasury": 18_000_000,
        "tax_income": 7_000_000,
        "daily_income": 4_000_000,
        "gold": 200,
        "gold_daily": 40,
        "oil_reserves": 12_000_000,
        "oil_production": 1_000,
        "grain": 100,
        "electricity": 120,
        "active_personnel": 170_000,
        "reserve_personnel": 450_000,
    },
    "iran": {
        "population": 90_000_000,
        "treasury": 45_000_000,
        "tax_income": 7_000_000,
        "daily_income": 14_000_000,
        "gold": 250,
        "gold_daily": 50,
        "oil_reserves": 250_000_000,
        "oil_production": 4_000_000,
        "grain": 35,
        "electricity": 130,
        "active_personnel": 610_000,
        "reserve_personnel": 1_200_000,
    },
    "germany": {
        "population": 84_000_000,
        "treasury": 55_000_000,
        "tax_income": 10_000_000,
        "daily_income": 18_000_000,
        "gold": 350,
        "gold_daily": 50,
        "oil_reserves": 40_000_000,
        "oil_production": 1_000_000,
        "grain": 45,
        "electricity": 155,
        "active_personnel": 185_000,
        "reserve_personnel": 800_000,
    },
    "china": {
        "population": 1_400_000_000,
        "treasury": 120_000_000,
        "tax_income": 18_000_000,
        "daily_income": 25_000_000,
        "gold": 700,
        "gold_daily": 80,
        "oil_reserves": 250_000_000,
        "oil_production": 4_500_000,
        "grain": 60,
        "electricity": 155,
        "active_personnel": 2_000_000,
        "reserve_personnel": 1_000_000,
    },
    "russia": {
        "population": 144_000_000,
        "treasury": 55_000_000,
        "tax_income": 12_000_000,
        "daily_income": 16_000_000,
        "gold": 400,
        "gold_daily": 60,
        "oil_reserves": 375_000_000,
        "oil_production": 4_000_000,
        "grain": 40,
        "electricity": 145,
        "active_personnel": 1_320_000,
        "reserve_personnel": 2_000_000,
    },
    "uk": {
        "population": 69_000_000,
        "treasury": 50_000_000,
        "tax_income": 10_000_000,
        "daily_income": 17_000_000,
        "gold": 350,
        "gold_daily": 50,
        "oil_reserves": 25_000_000,
        "oil_production": 1_000_000,
        "grain": 40,
        "electricity": 150,
        "active_personnel": 185_000,
        "reserve_personnel": 900_000,
    }
}

# ===== دسته‌بندی‌های دارایی‌های نظامی =====
ASSET_CATEGORIES = {
    "Aircraft":     ("✈️ نیروی هوایی", "فروند"),
    "Missiles":     ("🚀 موشکی", "قبضه"),
    "Air Defense":  ("🛡️ پدافند هوایی", "سامانه"),
    "Navy":         ("🚢 نیروی دریایی", "فروند"),
    "Ground Forces":("🚛 نیروی زمینی", "دستگاه"),
    "UAV":          ("🛩️ پهپادها", "فروند"),
    "Artillery":    ("🎯 توپخانه", "قبضه"),
}

# ===== کاتالوگ دقیق و جامع تجهیزات نظامی تمام کشورها =====
COUNTRY_EQUIPMENT_CATALOG = {

    # 🇫🇷 فرانسه (FRANCE) - کاتالوگ فوق‌العاده گسترده
    "france": [
        # نیروی هوایی
        {"key": "rafale_c",       "name": "Rafale C (نیروی هوایی)","category": "Aircraft",     "price": 18_000_000, "initial": 100,  "maint": 50_000, "producible": True},
        {"key": "rafale_b",       "name": "Rafale B (دوکابین)",   "category": "Aircraft",     "price": 18_000_000, "initial": 50,   "maint": 50_000, "producible": True},
        {"key": "rafale_m",       "name": "Rafale M (ناونشین)",   "category": "Aircraft",     "price": 20_000_000, "initial": 40,   "maint": 55_000, "producible": True},
        {"key": "mirage_2000d",  "name": "Mirage 2000D Strike",  "category": "Aircraft",     "price": 10_000_000, "initial": 65,   "maint": 30_000, "producible": True},
        {"key": "mirage_2000_5",  "name": "Mirage 2000-5 Fighter","category": "Aircraft",     "price": 10_000_000, "initial": 25,   "maint": 30_000, "producible": True},
        {"key": "a400m_fr",      "name": "A400M Atlas Transport","category": "Aircraft",     "price": 20_000_000, "initial": 20,   "maint": 40_000, "producible": True},
        {"key": "a330_mrtt_fr",  "name": "A330 MRTT Phénix Tanker","category":"Aircraft",   "price": 25_000_000, "initial": 12,   "maint": 50_000, "producible": True},
        {"key": "cn235_fr",      "name": "CN-235 Transport",     "category": "Aircraft",     "price": 6_000_000,  "initial": 27,   "maint": 15_000, "producible": True},
        {"key": "tiger_heli_fr", "name": "Eurocopter Tiger Attack","category":"Aircraft",    "price": 8_000_000,  "initial": 70,   "maint": 20_000, "producible": True},
        {"key": "nh90_fr",       "name": "NH90 Caïman Transport","category": "Aircraft",     "price": 6_000_000,  "initial": 70,   "maint": 15_000, "producible": True},
        {"key": "caracal_heli",  "name": "H225M Caracal Combat", "category": "Aircraft",     "price": 5_000_000,  "initial": 20,   "maint": 12_000, "producible": True},
        {"key": "cougar_heli",   "name": "AS532 Cougar Heli",    "category": "Aircraft",     "price": 4_000_000,  "initial": 25,   "maint": 10_000, "producible": True},
        {"key": "puma_heli",     "name": "SA330 Puma Heli",      "category": "Aircraft",     "price": 3_000_000,  "initial": 30,   "maint": 8_000,  "producible": True},
        {"key": "panther_heli",  "name": "AS565 Panther Heli",   "category": "Aircraft",     "price": 3_000_000,  "initial": 35,   "maint": 8_000,  "producible": True},
        {"key": "gazelle_heli",  "name": "SA342 Gazelle Heli",   "category": "Aircraft",     "price": 2_000_000,  "initial": 80,   "maint": 5_000,  "producible": True},

        # پهپادها
        {"key": "patroller_uav", "name": "Safran Patroller Recon","category": "UAV",          "price": 2_000_000,  "initial": 15,   "maint": 5_000,  "producible": True},
        {"key": "drac_uav",      "name": "DRAC Recon Drone",     "category": "UAV",          "price": 300_000,    "initial": 60,   "maint": 800,    "producible": True},
        {"key": "tactical_drones_fr","name":"پهپادهای شناسایی تاکتیکی","category":"UAV",      "price": 400_000,    "initial": 150,  "maint": 1_000,  "producible": True},

        # نیروی زمینی
        {"key": "leclerc_tank",  "name": "Leclerc Tank",         "category": "Ground Forces","price": 4_000_000,  "initial": 220,  "maint": 9_000,  "producible": True},
        {"key": "vbci_ifv",      "name": "VBCI Armored Vehicle", "category": "Ground Forces","price": 1_500_000,  "initial": 600,  "maint": 3_500,  "producible": True},
        {"key": "griffon_apc",   "name": "Griffon VBMR",         "category": "Ground Forces","price": 1_000_000,  "initial": 500,  "maint": 2_500,  "producible": True},
        {"key": "serval_apc",    "name": "Serval VBMR-L",        "category": "Ground Forces","price": 800_000,    "initial": 200,  "maint": 2_000,  "producible": True},
        {"key": "jaguar_ebrc",   "name": "Jaguar EBRC Armored",  "category": "Ground Forces","price": 1_800_000,  "initial": 60,   "maint": 4_000,  "producible": True},
        {"key": "amx10rc",       "name": "AMX-10RC Armored",     "category": "Ground Forces","price": 1_000_000,  "initial": 200,  "maint": 2_500,  "producible": True},
        {"key": "vab_apc_fr",    "name": "VAB APC",              "category": "Ground Forces","price": 500_000,    "initial": 1500, "maint": 1_200,  "producible": True},
        {"key": "pvp_armored",   "name": "PVP Light Armored",    "category": "Ground Forces","price": 200_000,    "initial": 1000, "maint": 500,    "producible": True},
        {"key": "vt4_utility",   "name": "VT4 Tactical Vehicle", "category": "Ground Forces","price": 100_000,    "initial": 3000, "maint": 300,    "producible": True},

        # توپخانه
        {"key": "caesar_art",    "name": "CAESAR 155mm Howitzer","category": "Artillery",    "price": 2_000_000,  "initial": 80,   "maint": 5_000,  "producible": True},
        {"key": "trf1_howitzer", "name": "TRF1 155mm Towed",     "category": "Artillery",    "price": 500_000,    "initial": 30,   "maint": 1_200,  "producible": True},
        {"key": "rtf1_mortar",   "name": "MO-120-RT Heavy Mortar","category":"Artillery",    "price": 200_000,    "initial": 120,  "maint": 500,    "producible": True},

        # نیروی دریایی
        {"key": "charles_de_gaulle","name":"Charles de Gaulle Carrier","category": "Navy",   "price": 95_000_000, "initial": 1,    "maint": 500_000,"producible": True},
        {"key": "mistral_lhd_fr","name": "Mistral Class LHD",     "category": "Navy",         "price": 50_000_000, "initial": 3,    "maint": 250_000,"producible": True},
        {"key": "horizon_destroyer","name":"Horizon Class Destroyer","category": "Navy",     "price": 30_000_000, "initial": 2,    "maint": 100_000,"producible": True},
        {"key": "fremm_frigate", "name": "FREMM Aquitaine Class","category": "Navy",         "price": 25_000_000, "initial": 8,    "maint": 90_000, "producible": True},
        {"key": "lafayette_frigate","name":"La Fayette Frigate",  "category": "Navy",         "price": 15_000_000, "initial": 5,    "maint": 50_000, "producible": True},
        {"key": "floreal_frigate","name":"Floréal Class Frigate", "category": "Navy",         "price": 12_000_000, "initial": 6,    "maint": 40_000, "producible": True},
        {"key": "destienne_corv","name": "D'Estienne d'Orves Corv","category": "Navy",       "price": 8_000_000,  "initial": 6,    "maint": 25_000, "producible": True},
        {"key": "patrol_ships_fr","name":"شناورهای گشتی و رزمی", "category": "Navy",         "price": 1_000_000,  "initial": 40,   "maint": 3_000,  "producible": True},
        {"key": "suffren_sub",   "name": "Suffren SSN Submarine", "category": "Navy",         "price": 35_000_000, "initial": 2,    "maint": 150_000,"producible": True},
        {"key": "rubis_sub",     "name": "Rubis / Améthyste Sub", "category": "Navy",         "price": 25_000_000, "initial": 4,    "maint": 100_000,"producible": True},
        {"key": "triomphant_sub","name": "Triomphant SSBN Sub",  "category": "Navy",         "price": 50_000_000, "initial": 4,    "maint": 220_000,"producible": True},

        # توان موشکی
        {"key": "m51_slbm",      "name": "M51 SLBM Nuclear",     "category": "Missiles",     "price": 15_000_000, "initial": 48,   "maint": 35_000, "producible": True},
        {"key": "asmp_a_missile","name": "ASMP-A Nuclear Cruise","category": "Missiles",     "price": 10_000_000, "initial": 50,   "maint": 25_000, "producible": True},
        {"key": "scalp_eg",      "name": "SCALP EG Cruise",      "category": "Missiles",     "price": 2_000_000,  "initial": 300,  "maint": 3_000,  "producible": True},
        {"key": "exocet",        "name": "Exocet MM40 Anti-Ship","category": "Missiles",     "price": 1_200_000,  "initial": 300,  "maint": 2_000,  "producible": True},
        {"key": "meteor_fr",     "name": "Meteor BVR Air-to-Air","category": "Missiles",     "price": 1_500_000,  "initial": 300,  "maint": 2_000,  "producible": True},
        {"key": "mica_fr",       "name": "MICA Air-to-Air",      "category": "Missiles",     "price": 800_000,    "initial": 500,  "maint": 1_200,  "producible": True},
        {"key": "aster_missiles","name": "Aster 15 / Aster 30",  "category": "Missiles",     "price": 2_000_000,  "initial": 400,  "maint": 3_000,  "producible": True},
        {"key": "akeron_mp",     "name": "Akeron MP Anti-Tank",  "category": "Missiles",     "price": 300_000,    "initial": 500,  "maint": 500,    "producible": True},
        {"key": "milan_atgm",    "name": "MILAN Anti-Tank",      "category": "Missiles",     "price": 150_000,    "initial": 300,  "maint": 300,    "producible": True},

        # پدافند هوایی
        {"key": "samp_t",        "name": "SAMP/T Air Defense",   "category": "Air Defense",  "price": 12_000_000, "initial": 10,   "maint": 35_000, "producible": True},
        {"key": "crotale_ng",    "name": "Crotale NG System",    "category": "Air Defense",  "price": 4_000_000,  "initial": 12,   "maint": 12_000, "producible": True},
        {"key": "mistral_manpads","name":"Mistral MANPADS",       "category": "Air Defense",  "price": 500_000,    "initial": 100,  "maint": 1_000,  "producible": True},
        {"key": "radars_fr",     "name": "رادارهای نظامی",       "category": "Air Defense",  "price": 4_000_000,  "initial": 100,  "maint": 12_000, "producible": True},

        # وارداتی (producible=False)
        {"key": "c130j_fr",      "name": "C-130J (وارداتی)",     "category": "Aircraft",     "price": 8_000_000,  "initial": 8,    "maint": 18_000, "producible": False},
        {"key": "e3f_awacs",     "name": "E-3F AWACS (وارداتی)",  "category": "Aircraft",     "price": 25_000_000, "initial": 4,    "maint": 50_000, "producible": False},
        {"key": "e2c_hawkeye_fr","name": "E-2C Hawkeye (وارداتی)","category":"Aircraft",    "price": 12_000_000, "initial": 3,    "maint": 25_000, "producible": False},
        {"key": "reaper_fr",     "name": "MQ-9 Reaper (وارداتی)","category": "UAV",          "price": 3_000_000,  "initial": 12,   "maint": 10_000, "producible": False},
        {"key": "lrm_mlrs",      "name": "LRM MLRS (وارداتی)",    "category": "Artillery",    "price": 2_500_000,  "initial": 13,   "maint": 6_000,  "producible": False},
    ],

    # 🇺🇦 اوکراین (UKRAINE)
    "ukraine": [
        # تولید بومی (producible=True)
        {"key": "btr4_ukraine",   "name": "BTR-4 Bucephalus APC","category": "Ground Forces","price": 1_000_000,  "initial": 200,  "maint": 2_500, "producible": True},
        {"key": "btr3_ukraine",   "name": "BTR-3 APC",            "category": "Ground Forces","price": 800_000,    "initial": 150,  "maint": 2_000, "producible": True},
        {"key": "fpv_kamikaze",   "name": "FPV Kamikaze Drones",  "category": "UAV",          "price": 50_000,     "initial": 2000, "maint": 100,   "producible": True},
        {"key": "leleka_uav",     "name": "Leleka-100 Recon UAV", "category": "UAV",          "price": 200_000,    "initial": 120,  "maint": 500,   "producible": True},
        {"key": "shark_uav",      "name": "Shark Recon UAV",      "category": "UAV",          "price": 300_000,    "initial": 60,   "maint": 800,   "producible": True},
        {"key": "punisher_uav",   "name": "Punisher Strike UAV",  "category": "UAV",          "price": 400_000,    "initial": 50,   "maint": 1_000, "producible": True},
        {"key": "bober_uav",      "name": "Bober / UJ-22 UAV",    "category": "UAV",          "price": 500_000,    "initial": 100,  "maint": 1_200, "producible": True},
        {"key": "pd2_uav",        "name": "PD-2 Recon UAV",       "category": "UAV",          "price": 400_000,    "initial": 30,   "maint": 1_000, "producible": True},
        {"key": "bohdana_art",    "name": "Bohdana 155mm Howitzer","category": "Artillery",   "price": 2_000_000,  "initial": 30,   "maint": 5_000, "producible": True},
        {"key": "sea_baby_usv",   "name": "Sea Baby USV Drones",  "category": "Navy",         "price": 100_000,    "initial": 100,  "maint": 300,   "producible": True},
        {"key": "magura_v5",      "name": "Magura V5 USV Drones", "category": "Navy",         "price": 150_000,    "initial": 50,   "maint": 400,   "producible": True},
        {"key": "gurza_m",        "name": "Gurza-M Gunboat",      "category": "Navy",         "price": 1_000_000,  "initial": 6,    "maint": 3_000, "producible": True},
        {"key": "stugna_p",       "name": "Stugna-P ATGM",        "category": "Missiles",     "price": 200_000,    "initial": 500,  "maint": 300,   "producible": True},
        {"key": "corsar_atgm",    "name": "Corsar ATGM",          "category": "Missiles",     "price": 150_000,    "initial": 300,  "maint": 200,   "producible": True},
        {"key": "neptune_missile","name": "Neptune Anti-Ship",    "category": "Missiles",     "price": 1_000_000,  "initial": 50,   "maint": 2_000, "producible": True},
        {"key": "vilkha_rocket",  "name": "Vilkha Heavy Rocket",  "category": "Missiles",     "price": 1_500_000,  "initial": 40,   "maint": 3_000, "producible": True},

        # وارداتی / کمکی / قدیمی (producible=False)
        {"key": "f16_ukraine",    "name": "F-16 Falcon (کمکی)",   "category": "Aircraft",     "price": 8_000_000,  "initial": 12,   "maint": 20_000,"producible": False},
        {"key": "su27_ukraine",   "name": "Su-27 (قدیمی)",        "category": "Aircraft",     "price": 8_000_000,  "initial": 30,   "maint": 22_000,"producible": False},
        {"key": "mig29_ukraine",  "name": "MiG-29 (قدیمی)",       "category": "Aircraft",     "price": 7_000_000,  "initial": 40,   "maint": 20_000,"producible": False},
        {"key": "su24_ukraine",   "name": "Su-24M (قدیمی)",       "category": "Aircraft",     "price": 10_000_000, "initial": 15,   "maint": 30_000,"producible": False},
        {"key": "su25_ukraine",   "name": "Su-25 (قدیمی)",        "category": "Aircraft",     "price": 6_000_000,  "initial": 15,   "maint": 18_000,"producible": False},
        {"key": "l39_albatros",   "name": "L-39 Albatros (قدیمی)","category": "Aircraft",     "price": 2_000_000,  "initial": 30,   "maint": 5_000, "producible": False},
        {"key": "an26_antonov",   "name": "Antonov Transport",    "category": "Aircraft",     "price": 5_000_000,  "initial": 20,   "maint": 12_000,"producible": False},
        {"key": "bayraktar_tb2_ukr","name":"Bayraktar TB2 (وارداتی)","category":"UAV",        "price": 500_000,    "initial": 30,   "maint": 1_000, "producible": False},
        {"key": "mi24_ukraine",   "name": "Mi-24 Hind (قدیمی)",   "category": "Aircraft",     "price": 4_000_000,  "initial": 25,   "maint": 10_000,"producible": False},
        {"key": "mi8_ukraine",    "name": "Mi-8 / Mi-17 (قدیمی)", "category": "Aircraft",     "price": 3_000_000,  "initial": 35,   "maint": 8_000, "producible": False},
        {"key": "blackhawk_ukr",  "name": "UH-60 Black Hawk (کمکی)","category":"Aircraft",   "price": 3_000_000,  "initial": 2,    "maint": 8_000, "producible": False},
        {"key": "seaking_ukr",    "name": "Westland Sea King (کمکی)","category":"Aircraft",  "price": 3_000_000,  "initial": 3,    "maint": 8_000, "producible": False},
        {"key": "t64_tank",       "name": "تانک T-64BV",          "category": "Ground Forces","price": 1_000_000,  "initial": 600,  "maint": 3_000, "producible": False},
        {"key": "t72_ukraine",    "name": "تانک T-72 (قدیمی)",    "category": "Ground Forces","price": 1_200_000,  "initial": 350,  "maint": 3_500, "producible": False},
        {"key": "t80_ukraine",    "name": "تانک T-80BV",          "category": "Ground Forces","price": 1_500_000,  "initial": 100,  "maint": 4_000, "producible": False},
        {"key": "pt91_twardy",    "name": "تانک PT-91 (کمکی)",    "category": "Ground Forces","price": 1_800_000,  "initial": 60,   "maint": 4_500, "producible": False},
        {"key": "leopard2_ukraine","name":"لئوپارد ۲ (کمکی)",     "category": "Ground Forces","price": 3_000_000,  "initial": 60,   "maint": 7_000, "producible": False},
        {"key": "m1a1_ukraine",   "name": "آبرامز M1A1 (کمکی)",   "category": "Ground Forces","price": 3_000_000,  "initial": 31,   "maint": 8_000, "producible": False},
        {"key": "challenger2_ukr","name": "چلنجر ۲ (کمکی)",       "category": "Ground Forces","price": 3_500_000,  "initial": 14,   "maint": 8_000, "producible": False},
        {"key": "bmp1_bmp2_ukr",  "name": "BMP-1 / BMP-2 (قدیمی)","category":"Ground Forces", "price": 600_000,    "initial": 800,  "maint": 1_500, "producible": False},
        {"key": "bradley_ukraine","name":"M2 Bradley (کمکی)",     "category": "Ground Forces","price": 1_200_000,  "initial": 150,  "maint": 3_000, "producible": False},
        {"key": "cv90_ifv",       "name": "CV90 IFV (کمکی)",      "category": "Ground Forces","price": 1_500_000,  "initial": 50,   "maint": 3_500, "producible": False},
        {"key": "marder_ukr",     "name": "Marder 1A3 (کمکی)",    "category": "Ground Forces","price": 1_000_000,  "initial": 90,   "maint": 2_500, "producible": False},
        {"key": "stryker_ukr",    "name": "Stryker APC (کمکی)",   "category": "Ground Forces","price": 800_000,    "initial": 90,   "maint": 2_000, "producible": False},
        {"key": "m113_ukraine",   "name": "M113 APC (کمکی)",      "category": "Ground Forces","price": 300_000,    "initial": 600,  "maint": 800,   "producible": False},
        {"key": "senator_mrap",   "name": "Senator Armored (کمکی)","category":"Ground Forces","price": 400_000,    "initial": 300,  "maint": 1_000, "producible": False},
        {"key": "maxxpro_mrap",   "name": "MaxxPro MRAP (کمکی)",  "category": "Ground Forces","price": 500_000,    "initial": 400,  "maint": 1_200, "producible": False},
        {"key": "bushmaster_mrap","name":"Bushmaster MRAP (کمکی)","category":"Ground Forces","price": 500_000,    "initial": 100,  "maint": 1_200, "producible": False},
        {"key": "humvee_ukr",     "name": "Humvee HMMWV (کمکی)",  "category": "Ground Forces","price": 100_000,    "initial": 2000, "maint": 300,   "producible": False},
        {"key": "m777_ukraine",   "name": "توپخانه M777 (کمکی)",  "category": "Artillery",    "price": 800_000,    "initial": 150,  "maint": 2_000, "producible": False},
        {"key": "gvozdika_art",   "name": "توپخانه ۲S1 (قدیمی)",  "category": "Artillery",    "price": 600_000,    "initial": 250,  "maint": 1_500, "producible": False},
        {"key": "msta_s_ukr",     "name": "۲S19 Msta-S (قدیمی)",  "category": "Artillery",    "price": 1_800_000,  "initial": 40,   "maint": 4_000, "producible": False},
        {"key": "krab_howitzer",  "name": "AHS Krab (کمکی)",      "category": "Artillery",    "price": 2_000_000,  "initial": 50,   "maint": 5_000, "producible": False},
        {"key": "caesar_ukraine", "name": "CAESAR 155mm (کمکی)",  "category": "Artillery",    "price": 2_000_000,  "initial": 30,   "maint": 5_000, "producible": False},
        {"key": "pzh2000_ukraine","name":"PzH 2000 (کمکی)",       "category": "Artillery",    "price": 2_500_000,  "initial": 30,   "maint": 6_000, "producible": False},
        {"key": "archer_art",     "name": "Archer Howitzer (کمکی)","category":"Artillery",    "price": 3_000_000,  "initial": 8,    "maint": 8_000, "producible": False},
        {"key": "himars_ukraine", "name": "هیمارس HIMARS (کمکی)","category": "Artillery",    "price": 3_000_000,  "initial": 38,   "maint": 8_000, "producible": False},
        {"key": "m270_ukraine",   "name": "M270 / MARS II (کمکی)","category":"Artillery",    "price": 2_500_000,  "initial": 12,   "maint": 6_000, "producible": False},
        {"key": "vampire_mlrs",   "name": "RM-70 Vampire (کمکی)",  "category": "Artillery",    "price": 1_500_000,  "initial": 30,   "maint": 3_500, "producible": False},
        {"key": "bm21_ukraine",   "name": "BM-21 Grad (قدیمی)",   "category": "Artillery",    "price": 500_000,    "initial": 150,  "maint": 1_200, "producible": False},
        {"key": "uragan_mlrs",    "name": "راکت‌انداز اوراگان",  "category": "Artillery",    "price": 1_200_000,  "initial": 30,   "maint": 3_000, "producible": False},
        {"key": "patrol_boat_ukr","name":"Island Patrol Boat",    "category": "Navy",         "price": 1_000_000,  "initial": 4,    "maint": 3_000, "producible": False},
        {"key": "mark6_boat",     "name": "Mark VI Patrol Boat",  "category": "Navy",         "price": 1_200_000,  "initial": 4,    "maint": 3_500, "producible": False},
        {"key": "javelin_atgm",   "name": "موشک جاولین Javelin",   "category": "Missiles",     "price": 200_000,    "initial": 1000, "maint": 400,   "producible": False},
        {"key": "nlaw_atgm",      "name": "موشک NLAW",            "category": "Missiles",     "price": 100_000,    "initial": 1500, "maint": 200,   "producible": False},
        {"key": "storm_shadow_ukr","name":"Storm Shadow / SCALP", "category": "Missiles",     "price": 2_000_000,  "initial": 80,   "maint": 3_000, "producible": False},
        {"key": "atacms_missile", "name": "موشک بالستیک ATACMS", "category": "Missiles",     "price": 3_000_000,  "initial": 50,   "maint": 5_000, "producible": False},
        {"key": "tochka_u",       "name": "توشکا Tochka-U",       "category": "Missiles",     "price": 1_500_000,  "initial": 30,   "maint": 3_000, "producible": False},
        {"key": "harm_missile_ukr","name":"AGM-88 HARM ضدرادار",  "category": "Missiles",     "price": 1_000_000,  "initial": 100,  "maint": 1_200, "producible": False},
        {"key": "patriot_ukraine","name":"پاتریوت PAC-3 (کمکی)",  "category": "Air Defense",  "price": 10_000_000, "initial": 3,    "maint": 30_000,"producible": False},
        {"key": "nasams_ukraine", "name": "سامانه NASAMS (کمکی)",  "category": "Air Defense",  "price": 8_000_000,  "initial": 5,    "maint": 25_000,"producible": False},
        {"key": "iris_t_ukraine", "name": "IRIS-T SLM (کمکی)",    "category": "Air Defense",  "price": 8_000_000,  "initial": 4,    "maint": 25_000,"producible": False},
        {"key": "samp_t_ukr",     "name": "SAMP/T MAMBA (کمکی)",  "category": "Air Defense",  "price": 12_000_000, "initial": 1,    "maint": 35_000,"producible": False},
        {"key": "s300_ukraine",   "name": "S-300PS/PT (قدیمی)",   "category": "Air Defense",  "price": 10_000_000, "initial": 15,   "maint": 25_000,"producible": False},
        {"key": "buk_m1_ukr",     "name": "Buk-M1 (قدیمی)",       "category": "Air Defense",  "price": 6_000_000,  "initial": 10,   "maint": 15_000,"producible": False},
        {"key": "gepard_spaag",   "name": "پدافند چرخدار Gepard", "category": "Air Defense",  "price": 1_500_000,  "initial": 45,   "maint": 4_000, "producible": False},
        {"key": "avenger_ukr",    "name": "Avenger System (کمکی)","category": "Air Defense",  "price": 2_000_000,  "initial": 12,   "maint": 5_000, "producible": False},
        {"key": "stormer_hvm_ukr","name":"Stormer HVM (کمکی)",    "category": "Air Defense",  "price": 1_500_000,  "initial": 15,   "maint": 3_500, "producible": False},
        {"key": "radars_ukraine", "name": "رادارهای نظامی",       "category": "Air Defense",  "price": 4_000_000,  "initial": 80,   "maint": 12_000,"producible": False},
    ],

    # 🇶🇦 دولت قطر (QATAR)
    "qatar": [
        # بومی (producible=True)
        {"key": "tactical_drones_qatar","name": "پهپادهای شناسایی تاکتیکی","category": "UAV",      "price": 400_000,    "initial": 50,   "maint": 1_000,  "producible": True},
        {"key": "combat_uavs_qatar",   "name": "پهپادهای رزمی و نظارتی", "category": "UAV",        "price": 1_500_000,  "initial": 30,   "maint": 4_000,  "producible": True},
        {"key": "patrol_ships_qatar",  "name": "شناورهای رزمی و گشتی",   "category": "Navy",       "price": 1_000_000,  "initial": 20,   "maint": 3_000,  "producible": True},
        {"key": "fast_attack_qatar",   "name": "قایق‌های تندرو",        "category": "Navy",       "price": 300_000,    "initial": 30,   "maint": 800,    "producible": True},
        {"key": "usv_drones_qatar",    "name": "شناورهای بدون سرنشین",   "category": "Navy",       "price": 200_000,    "initial": 15,   "maint": 500,    "producible": True},

        # وارداتی (producible=False)
        {"key": "rafale_qatar",        "name": "Rafale (وارداتی)",       "category": "Aircraft",   "price": 18_000_000, "initial": 36,   "maint": 50_000, "producible": False},
        {"key": "typhoon_qatar",       "name": "Eurofighter Typhoon (وارداتی)","category":"Aircraft","price":18_000_000,"initial": 24,   "maint": 50_000, "producible": False},
        {"key": "f15qa",               "name": "F-15QA Ababil (وارداتی)","category":"Aircraft",   "price": 15_000_000, "initial": 36,   "maint": 40_000, "producible": False},
        {"key": "mirage_2000_qatar",   "name": "Mirage 2000-5 (وارداتی)","category":"Aircraft",   "price": 10_000_000, "initial": 12,   "maint": 25_000, "producible": False},
        {"key": "c17_qatar",           "name": "C-17 Globemaster (وارداتی)","category":"Aircraft","price": 20_000_000, "initial": 8,    "maint": 45_000, "producible": False},
        {"key": "c130j_qatar",         "name": "C-130J Hercules (وارداتی)","category":"Aircraft", "price": 8_000_000,  "initial": 4,    "maint": 18_000, "producible": False},
        {"key": "recon_trainers_qatar","name": "شناسایی و آموزشی",      "category": "Aircraft",   "price": 2_000_000,  "initial": 15,   "maint": 5_000,  "producible": False},
        {"key": "ah64_qatar",          "name": "AH-64E Apache (وارداتی)","category":"Aircraft",   "price": 5_000_000,  "initial": 24,   "maint": 15_000, "producible": False},
        {"key": "nh90_qatar",          "name": "NH90 (وارداتی)",         "category": "Aircraft",   "price": 6_000_000,  "initial": 28,   "maint": 15_000, "producible": False},
        {"key": "aw139_qatar",         "name": "AW139 (وارداتی)",        "category": "Aircraft",   "price": 4_000_000,  "initial": 12,   "maint": 10_000, "producible": False},
        {"key": "aw109_qatar",         "name": "AW109 (وارداتی)",        "category": "Aircraft",   "price": 3_000_000,  "initial": 6,    "maint": 8_000,  "producible": False},
        {"key": "leopard_2a7_qatar",   "name": "Leopard 2A7+ (وارداتی)","category":"Ground Forces","price": 4_500_000, "initial": 62,   "maint": 10_000, "producible": False},
        {"key": "amx30_qatar",         "name": "AMX-30 (وارداتی)",       "category": "Ground Forces","price": 1_000_000,  "initial": 30,   "maint": 3_000,  "producible": False},
        {"key": "piranha_v",           "name": "Piranha V (وارداتی)",    "category": "Ground Forces","price": 1_200_000,  "initial": 90,   "maint": 3_000,  "producible": False},
        {"key": "vbci_qatar",          "name": "VBCI (وارداتی)",         "category": "Ground Forces","price": 1_500_000,  "initial": 24,   "maint": 3_500,  "producible": False},
        {"key": "vab_qatar",           "name": "VAB (وارداتی)",          "category": "Ground Forces","price": 600_000,    "initial": 40,   "maint": 1_500,  "producible": False},
        {"key": "light_armored_qatar", "name": "خودرو زرهی سبک",        "category": "Ground Forces","price": 300_000,    "initial": 300,  "maint": 800,    "producible": False},
        {"key": "pzh2000_qatar",       "name": "PzH 2000 (وارداتی)",     "category": "Artillery",    "price": 2_500_000,  "initial": 24,   "maint": 6_000,  "producible": False},
        {"key": "caesar_qatar",        "name": "CAESAR (وارداتی)",       "category": "Artillery",    "price": 2_000_000,  "initial": 12,   "maint": 5_000,  "producible": False},
        {"key": "himars_qatar",        "name": "HIMARS (وارداتی)",       "category": "Artillery",    "price": 3_000_000,  "initial": 7,    "maint": 8_000,  "producible": False},
        {"key": "rm70_mlrs",           "name": "RM-70 MLRS (وارداتی)",   "category": "Artillery",    "price": 1_500_000,  "initial": 20,   "maint": 3_500,  "producible": False},
        {"key": "missile_corvettes_qatar","name":"ناوچه موشک‌انداز (وارداتی)","category":"Navy",     "price": 18_000_000, "initial": 4,    "maint": 60_000, "producible": False},
        {"key": "meteor_qatar",        "name": "Meteor BVR (وارداتی)",   "category": "Missiles",     "price": 1_500_000,  "initial": 100,  "maint": 2_000,  "producible": False},
        {"key": "aim120_qatar",        "name": "AIM-120 AMRAAM (وارداتی)","category":"Missiles",   "price": 1_000_000,  "initial": 200,  "maint": 1_000,  "producible": False},
        {"key": "mica_air_qatar",      "name": "MICA (وارداتی)",         "category": "Missiles",     "price": 800_000,    "initial": 150,  "maint": 1_200,  "producible": False},
        {"key": "aim9x_qatar",         "name": "AIM-9X Sidewinder (وارداتی)","category":"Missiles", "price": 500_000,    "initial": 100,  "maint": 500,    "producible": False},
        {"key": "brimstone_qatar",     "name": "Brimstone (وارداتی)",    "category": "Missiles",     "price": 300_000,    "initial": 300,  "maint": 500,    "producible": False},
        {"key": "scalp_eg_qatar",      "name": "SCALP-EG Cruise (وارداتی)","category":"Missiles",   "price": 2_000_000,  "initial": 100,  "maint": 3_000,  "producible": False},
        {"key": "exocet_qatar",        "name": "Exocet Anti-Ship (وارداتی)","category":"Missiles",  "price": 1_200_000,  "initial": 50,   "maint": 2_000,  "producible": False},
        {"key": "patriot_qatar",       "name": "Patriot PAC-3 (وارداتی)","category":"Air Defense",  "price": 10_000_000, "initial": 2,    "maint": 30_000, "producible": False},
        {"key": "nasams_qatar",        "name": "NASAMS (وارداتی)",       "category": "Air Defense",  "price": 8_000_000,  "initial": 4,    "maint": 25_000, "producible": False},
        {"key": "mica_vl_qatar",       "name": "MICA VL (وارداتی)",      "category": "Air Defense",  "price": 6_000_000,  "initial": 2,    "maint": 18_000, "producible": False},
        {"key": "skyguard_qatar",      "name": "Skyguard (وارداتی)",     "category": "Air Defense",  "price": 2_000_000,  "initial": 6,    "maint": 5_000,  "producible": False},
        {"key": "radars_qatar",        "name": "رادارهای نظامی",       "category": "Air Defense",  "price": 4_000_000,  "initial": 30,   "maint": 12_000, "producible": False},
    ],

    # 🇺🇸 ایالات متحده آمریکا (USA)
    "usa": [
        # نیروی هوایی
        {"key": "f35a",           "name": "F-35A Lightning II",    "category": "Aircraft",     "price": 15_000_000, "initial": 400,  "maint": 50_000, "producible": True},
        {"key": "f35b",           "name": "F-35B Lightning II",    "category": "Aircraft",     "price": 16_000_000, "initial": 100,  "maint": 55_000, "producible": True},
        {"key": "f35c",           "name": "F-35C Lightning II",    "category": "Aircraft",     "price": 17_000_000, "initial": 80,   "maint": 60_000, "producible": True},
        {"key": "f22",            "name": "F-22 Raptor",          "category": "Aircraft",     "price": 25_000_000, "initial": 180,  "maint": 80_000, "producible": True},
        {"key": "f15e",           "name": "F-15E Strike Eagle",   "category": "Aircraft",     "price": 12_000_000, "initial": 220,  "maint": 35_000, "producible": True},
        {"key": "f15ex",          "name": "F-15EX Eagle II",      "category": "Aircraft",     "price": 15_000_000, "initial": 20,   "maint": 40_000, "producible": True},
        {"key": "f16",            "name": "F-16 Fighting Falcon", "category": "Aircraft",     "price": 8_000_000,  "initial": 700,  "maint": 20_000, "producible": True},
        {"key": "fa18ef",         "name": "F/A-18E/F Super Hornet","category": "Aircraft",    "price": 10_000_000, "initial": 550,  "maint": 30_000, "producible": True},
        {"key": "b1b",            "name": "B-1B Lancer Bomber",   "category": "Aircraft",     "price": 35_000_000, "initial": 40,   "maint": 110_000,"producible": True},
        {"key": "b2",             "name": "B-2 Spirit Bomber",    "category": "Aircraft",     "price": 50_000_000, "initial": 20,   "maint": 150_000,"producible": True},
        {"key": "b52h",           "name": "B-52H Stratofortress", "category": "Aircraft",     "price": 30_000_000, "initial": 70,   "maint": 100_000,"producible": True},
        {"key": "c17",            "name": "C-17 Globemaster III", "category": "Aircraft",     "price": 20_000_000, "initial": 220,  "maint": 45_000, "producible": True},
        {"key": "c130",           "name": "C-130 Hercules",       "category": "Aircraft",     "price": 6_000_000,  "initial": 300,  "maint": 15_000, "producible": True},
        {"key": "c5m",            "name": "C-5M Galaxy",          "category": "Aircraft",     "price": 30_000_000, "initial": 50,   "maint": 80_000, "producible": True},
        {"key": "kc135",          "name": "KC-135 Stratotanker",  "category": "Aircraft",     "price": 8_000_000,  "initial": 380,  "maint": 20_000, "producible": True},
        {"key": "kc46",           "name": "KC-46 Pegasus",        "category": "Aircraft",     "price": 12_000_000, "initial": 100,  "maint": 25_000, "producible": True},
        {"key": "e3_sentry",      "name": "E-3 Sentry AWACS",     "category": "Aircraft",     "price": 25_000_000, "initial": 20,   "maint": 50_000, "producible": True},
        {"key": "e7_wedgetail",   "name": "E-7 Wedgetail AWACS",  "category": "Aircraft",     "price": 30_000_000, "initial": 10,   "maint": 60_000, "producible": True},
        {"key": "rc135",          "name": "RC-135 Rivet Joint",   "category": "Aircraft",     "price": 20_000_000, "initial": 20,   "maint": 40_000, "producible": True},
        {"key": "u2_dragon",      "name": "U-2 Dragon Lady",      "category": "Aircraft",     "price": 15_000_000, "initial": 20,   "maint": 30_000, "producible": True},
        {"key": "ah64e",          "name": "AH-64E Apache",        "category": "Aircraft",     "price": 5_000_000,  "initial": 800,  "maint": 15_000, "producible": True},
        {"key": "uh60",           "name": "UH-60 Black Hawk",     "category": "Aircraft",     "price": 3_000_000,  "initial": 2000, "maint": 8_000,  "producible": True},
        {"key": "ch47",           "name": "CH-47 Chinook",        "category": "Aircraft",     "price": 6_000_000,  "initial": 500,  "maint": 15_000, "producible": True},
        {"key": "ah1z",           "name": "AH-1Z Viper",          "category": "Aircraft",     "price": 4_000_000,  "initial": 100,  "maint": 10_000, "producible": True},
        {"key": "v22",            "name": "V-22 Osprey",          "category": "Aircraft",     "price": 10_000_000, "initial": 400,  "maint": 25_000, "producible": True},
        {"key": "mh60",           "name": "MH-60 Seahawk",        "category": "Aircraft",     "price": 4_000_000,  "initial": 500,  "maint": 10_000, "producible": True},
        # پهپادها
        {"key": "mq9",            "name": "MQ-9 Reaper UAV",      "category": "UAV",          "price": 3_000_000,  "initial": 300,  "maint": 10_000, "producible": True},
        {"key": "rq4",            "name": "RQ-4 Global Hawk UAV", "category": "UAV",          "price": 15_000_000, "initial": 30,   "maint": 30_000, "producible": True},
        {"key": "mq1c",           "name": "MQ-1C Gray Eagle UAV", "category": "UAV",          "price": 2_000_000,  "initial": 100,  "maint": 5_000,  "producible": True},
        {"key": "tactical_drones","name": "Tactical Recon UAVs",  "category": "UAV",          "price": 500_000,    "initial": 300,  "maint": 1_000,  "producible": True},
        # نیروی زمینی
        {"key": "m1a2_abrams",    "name": "M1A2 Abrams Tank",     "category": "Ground Forces","price": 3_000_000,  "initial": 2500, "maint": 8_000,  "producible": True},
        {"key": "m1a1_abrams",    "name": "M1A1 Abrams Tank",     "category": "Ground Forces","price": 2_000_000,  "initial": 1000, "maint": 5_000,  "producible": True},
        {"key": "m2_bradley",     "name": "M2 Bradley IFV",       "category": "Ground Forces","price": 1_200_000,  "initial": 2500, "maint": 3_000,  "producible": True},
        {"key": "stryker",        "name": "Stryker APC",          "category": "Ground Forces","price": 800_000,    "initial": 5000, "maint": 2_000,  "producible": True},
        {"key": "m113_usa",       "name": "M113 APC",             "category": "Ground Forces","price": 300_000,    "initial": 1500, "maint": 800,    "producible": True},
        {"key": "jltv",           "name": "JLTV Tactical Vehicle","category": "Ground Forces","price": 400_000,    "initial": 10000,"maint": 1_000,  "producible": True},
        {"key": "light_armored",  "name": "Light Armored Vehicles","category": "Ground Forces","price": 500_000,   "initial": 6000, "maint": 1_200,  "producible": True},
        # توپخانه
        {"key": "m109_paladin",   "name": "M109 Paladin Howitzer","category": "Artillery",    "price": 1_500_000,  "initial": 900,  "maint": 4_000,  "producible": True},
        {"key": "m777",           "name": "M777 Howitzer",        "category": "Artillery",    "price": 800_000,    "initial": 800,  "maint": 2_000,  "producible": True},
        {"key": "himars",         "name": "HIMARS Rocket System", "category": "Artillery",    "price": 3_000_000,  "initial": 500,  "maint": 8_000,  "producible": True},
        {"key": "m270_mlrs",      "name": "M270 MLRS System",     "category": "Artillery",    "price": 2_500_000,  "initial": 300,  "maint": 6_000,  "producible": True},
        # نیروی دریایی
        {"key": "ford_class",     "name": "Ford Class Carrier",   "category": "Navy",         "price": 100_000_000,"initial": 3,    "maint": 500_000,"producible": True},
        {"key": "nimitz_class",   "name": "Nimitz Class Carrier", "category": "Navy",         "price": 80_000_000, "initial": 10,   "maint": 400_000,"producible": True},
        {"key": "america_class",  "name": "America Class Ship",   "category": "Navy",         "price": 30_000_000, "initial": 2,    "maint": 120_000,"producible": True},
        {"key": "wasp_class",     "name": "Wasp Class Ship",      "category": "Navy",         "price": 25_000_000, "initial": 8,    "maint": 100_000,"producible": True},
        {"key": "san_antonio",    "name": "San Antonio Class",    "category": "Navy",         "price": 15_000_000, "initial": 12,   "maint": 60_000, "producible": True},
        {"key": "harpers_ferry",  "name": "Harpers Ferry Class",  "category": "Navy",         "price": 10_000_000, "initial": 4,    "maint": 40_000, "producible": True},
        {"key": "whidbey_island", "name": "Whidbey Island Class", "category": "Navy",         "price": 10_000_000, "initial": 6,    "maint": 40_000, "producible": True},
        {"key": "burke_class",    "name": "Arleigh Burke Destroyer","category": "Navy",       "price": 20_000_000, "initial": 70,   "maint": 100_000,"producible": True},
        {"key": "zumwalt",        "name": "Zumwalt Destroyer",    "category": "Navy",         "price": 40_000_000, "initial": 3,    "maint": 180_000,"producible": True},
        {"key": "ticonderoga",    "name": "Ticonderoga Cruiser",  "category": "Navy",         "price": 25_000_000, "initial": 10,   "maint": 120_000,"producible": True},
        {"key": "lcs_ship",       "name": "Littoral Combat Ship", "category": "Navy",         "price": 8_000_000,  "initial": 20,   "maint": 30_000, "producible": True},
        {"key": "patrol_coastal", "name": "Patrol / Coastal Ships","category": "Navy",        "price": 1_000_000,  "initial": 70,   "maint": 3_000,  "producible": True},
        {"key": "supply_ships",   "name": "Supply Support Ships", "category": "Navy",         "price": 5_000_000,  "initial": 6,    "maint": 20_000, "producible": True},
        {"key": "puller_ships",   "name": "Lewis B. Puller Base", "category": "Navy",         "price": 8_000_000,  "initial": 2,    "maint": 30_000, "producible": True},
        {"key": "logistics_ships","name": "Logistics & Support Fleet","category":"Navy",     "price": 3_000_000,  "initial": 100,  "maint": 10_000, "producible": True},
        {"key": "virginia_class", "name": "Virginia Class Sub",   "category": "Navy",         "price": 35_000_000, "initial": 25,   "maint": 150_000,"producible": True},
        {"key": "los_angeles_sub","name": "Los Angeles Class Sub","category": "Navy",         "price": 20_000_000, "initial": 20,   "maint": 90_000, "producible": True},
        {"key": "seawolf_sub",    "name": "Seawolf Class Sub",    "category": "Navy",         "price": 45_000_000, "initial": 3,    "maint": 200_000,"producible": True},
        {"key": "ohio_ssbn",      "name": "Ohio Class SSBN Sub",  "category": "Navy",         "price": 50_000_000, "initial": 14,   "maint": 220_000,"producible": True},
        {"key": "ohio_ssgn",      "name": "Ohio Class SSGN Sub",  "category": "Navy",         "price": 40_000_000, "initial": 4,    "maint": 180_000,"producible": True},
        # توان موشکی
        {"key": "tomahawk",       "name": "Tomahawk Cruise Missile","category": "Missiles",   "price": 2_000_000,  "initial": 2000, "maint": 2_000,  "producible": True},
        {"key": "sm6",            "name": "SM-6 Missile",         "category": "Missiles",     "price": 3_000_000,  "initial": 500,  "maint": 4_000,  "producible": True},
        {"key": "sm3",            "name": "SM-3 Anti-Ballistic",  "category": "Missiles",     "price": 10_000_000, "initial": 300,  "maint": 15_000, "producible": True},
        {"key": "aim120",         "name": "AIM-120 AMRAAM",       "category": "Missiles",     "price": 1_000_000,  "initial": 1500, "maint": 1_000,  "producible": True},
        {"key": "aim9x",          "name": "AIM-9X Sidewinder",    "category": "Missiles",     "price": 500_000,    "initial": 1000, "maint": 500,    "producible": True},
        {"key": "jassm",          "name": "AGM-158 JASSM",        "category": "Missiles",     "price": 1_500_000,  "initial": 500,  "maint": 2_000,  "producible": True},
        {"key": "lrasm",          "name": "AGM-158C LRASM",       "category": "Missiles",     "price": 3_000_000,  "initial": 300,  "maint": 4_000,  "producible": True},
        {"key": "harm_aargm",     "name": "AGM-88 HARM/AARGM",    "category": "Missiles",     "price": 1_000_000,  "initial": 500,  "maint": 1_200,  "producible": True},
        {"key": "hellfire",       "name": "AGM-114 Hellfire",     "category": "Missiles",     "price": 150_000,    "initial": 3000, "maint": 200,    "producible": True},
        # پدافند هوایی
        {"key": "patriot_pac3",   "name": "Patriot PAC-3",        "category": "Air Defense",  "price": 10_000_000, "initial": 60,   "maint": 30_000, "producible": True},
        {"key": "thaad",          "name": "THAAD Battery",        "category": "Air Defense",  "price": 40_000_000, "initial": 10,   "maint": 100_000,"producible": True},
        {"key": "nasams",         "name": "NASAMS System",        "category": "Air Defense",  "price": 8_000_000,  "initial": 15,   "maint": 25_000, "producible": True},
        {"key": "avenger",        "name": "Avenger Air Defense",  "category": "Air Defense",  "price": 2_000_000,  "initial": 100,  "maint": 5_000,  "producible": True},
        {"key": "military_radars","name": "Military Radars",      "category": "Air Defense",  "price": 5_000_000,  "initial": 250,  "maint": 15_000, "producible": True},
    ],

    # 🇮🇱 اسرائیل (ISRAEL)
    "israel": [
        # تولید بومی (producible=True)
        {"key": "merkava_mk4",    "name": "مرکاوا Mk4",           "category": "Ground Forces","price": 3_500_000,  "initial": 700,  "maint": 8_000, "producible": True},
        {"key": "merkava_mk3",    "name": "مرکاوا Mk3",           "category": "Ground Forces","price": 2_000_000,  "initial": 500,  "maint": 5_000, "producible": True},
        {"key": "merkava_barak",  "name": "مرکاوا باراک",          "category": "Ground Forces","price": 5_000_000,  "initial": 50,   "maint": 12_000,"producible": True},
        {"key": "namer_apc",      "name": "نفربر نمر (Namer)",    "category": "Ground Forces","price": 2_000_000,  "initial": 300,  "maint": 4_000, "producible": True},
        {"key": "achzarit_apc",   "name": "نفربر آخزاریت",        "category": "Ground Forces","price": 1_000_000,  "initial": 200,  "maint": 2_000, "producible": True},
        {"key": "eitan_apc",      "name": "نفربر ایوتان (Eitan)",  "category": "Ground Forces","price": 1_500_000,  "initial": 50,   "maint": 3_000, "producible": True},
        {"key": "hermes_450",     "name": "پهپاد هرمس ۴۵۰",       "category": "UAV",          "price": 1_000_000,  "initial": 50,   "maint": 3_000, "producible": True},
        {"key": "hermes_900",     "name": "پهپاد هرمس ۹۰۰",       "category": "UAV",          "price": 2_500_000,  "initial": 30,   "maint": 7_000, "producible": True},
        {"key": "heron_tp",       "name": "پهپاد هرون TP ایوتان", "category": "UAV",          "price": 4_000_000,  "initial": 20,   "maint": 10_000,"producible": True},
        {"key": "harpy_drone",    "name": "پهپاد انتحاری هارپی",  "category": "UAV",          "price": 200_000,    "initial": 200,  "maint": 500,   "producible": True},
        {"key": "iron_dome",      "name": "سامانه گنبد آهنین",    "category": "Air Defense",  "price": 10_000_000, "initial": 15,   "maint": 30_000,"producible": True},
        {"key": "davids_sling",   "name": "سامانه فلاخن داوود",   "category": "Air Defense",  "price": 20_000_000, "initial": 5,    "maint": 50_000,"producible": True},
        {"key": "arrow_3",        "name": "سامانه پیکان ۲ و ۳",   "category": "Air Defense",  "price": 30_000_000, "initial": 6,    "maint": 80_000,"producible": True},
        {"key": "jericho_3",      "name": "موشک بالستیک جریکو ۳", "category": "Missiles",     "price": 15_000_000, "initial": 30,   "maint": 40_000,"producible": True},
        {"key": "jericho_2",      "name": "موشک بالستیک جریکو ۲", "category": "Missiles",     "price": 8_000_000,  "initial": 50,   "maint": 20_000,"producible": True},
        {"key": "popeye_missile", "name": "موشک کروز پاپای",     "category": "Missiles",     "price": 1_500_000,  "initial": 300,  "maint": 2_000, "producible": True},
        {"key": "delilah_missile","name": "موشک کروز دلیله",     "category": "Missiles",     "price": 1_000_000,  "initial": 400,  "maint": 1_500, "producible": True},
        {"key": "spike_missile",  "name": "موشک ضدتانک اسپایک",   "category": "Missiles",     "price": 200_000,    "initial": 1000, "maint": 300,   "producible": True},
        {"key": "super_dvora",    "name": "شناور سوپر دبورا",     "category": "Navy",         "price": 800_000,    "initial": 15,   "maint": 2_000, "producible": True},
        {"key": "patrol_vessels", "name": "شناورهای گشتی",        "category": "Navy",         "price": 500_000,    "initial": 50,   "maint": 1_000, "producible": True},

        # وارداتی (producible=False)
        {"key": "f35i_adir",      "name": "F-35I Adir (وارداتی)", "category": "Aircraft",     "price": 18_000_000, "initial": 40,   "maint": 60_000,"producible": False},
        {"key": "f15_israel",     "name": "F-15 Eagle (وارداتی)", "category": "Aircraft",     "price": 12_000_000, "initial": 80,   "maint": 35_000,"producible": False},
        {"key": "f16_israel",     "name": "F-16 Falcon (وارداتی)","category": "Aircraft",     "price": 8_000_000,  "initial": 170,  "maint": 20_000,"producible": False},
        {"key": "c130_hercules",  "name": "C-130 Hercules (وارداتی)","category":"Aircraft",   "price": 6_000_000,  "initial": 10,   "maint": 15_000,"producible": False},
        {"key": "kc707_reem",     "name": "KC-707 Re'em (وارداتی)","category":"Aircraft",    "price": 10_000_000, "initial": 5,    "maint": 25_000,"producible": False},
        {"key": "gulfstream_g550","name": "Gulfstream G550 (وارداتی)","category":"Aircraft", "price": 15_000_000, "initial": 10,   "maint": 30_000,"producible": False},
        {"key": "e2c_hawkeye",    "name": "E-2C Hawkeye (وارداتی)","category":"Aircraft",    "price": 12_000_000, "initial": 5,    "maint": 25_000,"producible": False},
        {"key": "ah64_apache",    "name": "AH-64 Apache (وارداتی)","category":"Aircraft",    "price": 5_000_000,  "initial": 50,   "maint": 15_000,"producible": False},
        {"key": "ch53_yasur",     "name": "CH-53 Yasur (وارداتی)","category":"Aircraft",     "price": 7_000_000,  "initial": 20,   "maint": 18_000,"producible": False},
        {"key": "uh60_blackhawk", "name": "UH-60 Black Hawk (وارداتی)","category":"Aircraft", "price": 3_000_000,  "initial": 50,   "maint": 8_000, "producible": False},
        {"key": "m113_apc",       "name": "نفربر M113 (وارداتی)", "category": "Ground Forces","price": 300_000,    "initial": 5000, "maint": 800,   "producible": False},
        {"key": "m109_doher",     "name": "M109 Doher (وارداتی)", "category": "Artillery",    "price": 1_200_000,  "initial": 400,  "maint": 3_000, "producible": False},
        {"key": "atmos_2000",     "name": "ATMOS 2000 (وارداتی)", "category": "Artillery",    "price": 2_000_000,  "initial": 40,   "maint": 5_000, "producible": False},
        {"key": "m270_mlrs",      "name": "M270 MLRS (وارداتی)",  "category": "Artillery",    "price": 2_500_000,  "initial": 50,   "maint": 6_000, "producible": False},
        {"key": "saar_6",         "name": "ناوچه Sa'ar 6 (وارداتی)","category":"Navy",       "price": 30_000_000, "initial": 4,    "maint": 100_000,"producible": False},
        {"key": "saar_5",         "name": "ناوچه Sa'ar 5 (وارداتی)","category":"Navy",       "price": 18_000_000, "initial": 3,    "maint": 60_000, "producible": False},
        {"key": "dolphin_sub",    "name": "زیردریایی دولفین (وارداتی)","category":"Navy",    "price": 40_000_000, "initial": 6,    "maint": 150_000,"producible": False},
        {"key": "patriot_israel", "name": "پاتریوت (وارداتی)",    "category": "Air Defense",  "price": 8_000_000,  "initial": 8,    "maint": 20_000, "producible": False},
    ],

    # 🇮🇷 جمهوری اسلامی ایران (IRAN)
    "iran": [
        # تولید بومی (producible=True)
        {"key": "shahed136",      "name": "شاهد-۱۳۶",             "category": "UAV",          "price": 100_000,    "initial": 2500, "maint": 500,  "producible": True},
        {"key": "shahed129",      "name": "شاهد-۱۲۹",             "category": "UAV",          "price": 800_000,    "initial": 200,  "maint": 3_000, "producible": True},
        {"key": "shahed191",      "name": "شاهد-۱۹۱",             "category": "UAV",          "price": 1_000_000,  "initial": 100,  "maint": 4_000, "producible": True},
        {"key": "mohajer6",       "name": "مهاجر-۶",              "category": "UAV",          "price": 500_000,    "initial": 300,  "maint": 2_000, "producible": True},
        {"key": "ababil_drone",   "name": "ابابیل",               "category": "UAV",          "price": 300_000,    "initial": 500,  "maint": 1_000, "producible": True},
        {"key": "kaman22",        "name": "کمان-۲۲",             "category": "UAV",          "price": 1_500_000,  "initial": 50,   "maint": 5_000, "producible": True},
        {"key": "zulfiqar_tank",  "name": "تانک ذوالفقار",        "category": "Ground Forces","price": 2_000_000,  "initial": 200,  "maint": 5_000, "producible": True},
        {"key": "karrar_tank",    "name": "تانک کرار",            "category": "Ground Forces","price": 2_500_000,  "initial": 100,  "maint": 6_000, "producible": True},
        {"key": "fajr_rocket",    "name": "راکت‌انداز فجر",       "category": "Artillery",    "price": 800_000,    "initial": 500,  "maint": 2_000, "producible": True},
        {"key": "zelzal_rocket",  "name": "راکت سنگین زلزال",     "category": "Artillery",    "price": 1_200_000,  "initial": 200,  "maint": 3_000, "producible": True},
        {"key": "fateh110",       "name": "موشک فاتح-۱۱۰",        "category": "Missiles",     "price": 1_000_000,  "initial": 500,  "maint": 1_500, "producible": True},
        {"key": "fateh313",       "name": "موشک فاتح-۳۱۳",        "category": "Missiles",     "price": 1_200_000,  "initial": 300,  "maint": 2_000, "producible": True},
        {"key": "zolfaghar_m",    "name": "موشک ذوالفقار",        "category": "Missiles",     "price": 2_000_000,  "initial": 200,  "maint": 3_000, "producible": True},
        {"key": "dezful_m",       "name": "موشک دزفول",           "category": "Missiles",     "price": 2_500_000,  "initial": 200,  "maint": 4_000, "producible": True},
        {"key": "qiam_m",         "name": "موشک قیام",            "category": "Missiles",     "price": 2_000_000,  "initial": 200,  "maint": 3_000, "producible": True},
        {"key": "ghadr_m",        "name": "موشک قدر",             "category": "Missiles",     "price": 3_000_000,  "initial": 150,  "maint": 5_000, "producible": True},
        {"key": "emad_m",         "name": "موشک عماد",            "category": "Missiles",     "price": 3_500_000,  "initial": 100,  "maint": 6_000, "producible": True},
        {"key": "haj_qasem",      "name": "موشک حاج قاسم",        "category": "Missiles",     "price": 4_000_000,  "initial": 100,  "maint": 7_000, "producible": True},
        {"key": "kheybar_shekan", "name": "موشک خیبرشکن",        "category": "Missiles",     "price": 3_000_000,  "initial": 100,  "maint": 5_000, "producible": True},
        {"key": "khorramshahr",   "name": "موشک خرمشهر",          "category": "Missiles",     "price": 5_000_000,  "initial": 100,  "maint": 8_000, "producible": True},
        {"key": "sejjil",         "name": "موشک سجیل",            "category": "Missiles",     "price": 6_000_000,  "initial": 50,   "maint": 10_000,"producible": True},
        {"key": "fattah1",        "name": "فتاح-۱ هایپرسونیک",    "category": "Missiles",     "price": 5_000_000,  "initial": 40,   "maint": 8_000, "producible": True},
        {"key": "fattah2",        "name": "فتاح-۲ هایپرسونیک",    "category": "Missiles",     "price": 7_000_000,  "initial": 30,   "maint": 10_000,"producible": True},
        {"key": "qasem_basir",    "name": "موشک قاسم بصیر",       "category": "Missiles",     "price": 4_000_000,  "initial": 30,   "maint": 6_000, "producible": True},
        {"key": "soumar_cruise",  "name": "کروز سومار",           "category": "Missiles",     "price": 1_500_000,  "initial": 100,  "maint": 2_500, "producible": True},
        {"key": "hoveyzeh_c",     "name": "کروز هویزه",           "category": "Missiles",     "price": 1_800_000,  "initial": 100,  "maint": 3_000, "producible": True},
        {"key": "paveh_c",        "name": "کروز پاوه",            "category": "Missiles",     "price": 2_000_000,  "initial": 50,   "maint": 3_500, "producible": True},
        {"key": "noor_antiship",  "name": "ضدکشتی نور",          "category": "Missiles",     "price": 800_000,    "initial": 500,  "maint": 1_200, "producible": True},
        {"key": "qader_antiship", "name": "ضدکشتی قادر",          "category": "Missiles",     "price": 1_200_000,  "initial": 200,  "maint": 2_000, "producible": True},
        {"key": "qadir_antiship", "name": "ضدکشتی قدیر",          "category": "Missiles",     "price": 1_500_000,  "initial": 100,  "maint": 2_500, "producible": True},
        {"key": "khalij_fars",    "name": "ضدکشتی خلیج فارس",     "category": "Missiles",     "price": 1_500_000,  "initial": 200,  "maint": 2_500, "producible": True},
        {"key": "zolfaghar_nav",  "name": "ذوالفقار دریایی",       "category": "Missiles",     "price": 2_000_000,  "initial": 100,  "maint": 3_000, "producible": True},
        {"key": "moudge_frigate", "name": "ناوچه کلاس موج",       "category": "Navy",         "price": 15_000_000, "initial": 4,    "maint": 50_000, "producible": True},
        {"key": "fast_attack",    "name": "قایق تندرو رزمی",      "category": "Navy",         "price": 200_000,    "initial": 1500, "maint": 500,   "producible": True},
        {"key": "missile_corv",   "name": "شناور موشک‌انداز",     "category": "Navy",         "price": 1_000_000,  "initial": 200,  "maint": 3_000, "producible": True},
        {"key": "patrol_iran",    "name": "شناور گشتی",           "category": "Navy",         "price": 300_000,    "initial": 300,  "maint": 800,   "producible": True},
        {"key": "usv_drones",     "name": "شناور بی‌سرنشین دریایی","category": "Navy",        "price": 200_000,    "initial": 150,  "maint": 500,   "producible": True},
        {"key": "fateh_sub",      "name": "زیردریایی کلاس فاتح",  "category": "Navy",         "price": 15_000_000, "initial": 2,    "maint": 50_000, "producible": True},
        {"key": "ghadir_sub",     "name": "زیردریایی کلاس غدیر",  "category": "Navy",         "price": 3_000_000,  "initial": 20,   "maint": 10_000, "producible": True},
        {"key": "midget_subs",    "name": "زیردریایی میدجت",      "category": "Navy",         "price": 1_000_000,  "initial": 30,   "maint": 3_000, "producible": True},
        {"key": "bavar373",       "name": "پدافند باور-۳۷۳",      "category": "Air Defense",  "price": 10_000_000, "initial": 10,   "maint": 30_000, "producible": True},
        {"key": "khordad_3",      "name": "پدافند سوم خرداد",     "category": "Air Defense",  "price": 5_000_000,  "initial": 20,   "maint": 15_000, "producible": True},
        {"key": "khordad_15",     "name": "پدافند ۱۵ خرداد",      "category": "Air Defense",  "price": 6_000_000,  "initial": 20,   "maint": 18_000, "producible": True},
        {"key": "talash_sys",     "name": "پدافند تلاش",          "category": "Air Defense",  "price": 5_000_000,  "initial": 20,   "maint": 15_000, "producible": True},
        {"key": "tabas_sys",      "name": "پدافند طبس",           "category": "Air Defense",  "price": 4_000_000,  "initial": 20,   "maint": 12_000, "producible": True},

        # وارداتی (producible=False)
        {"key": "f14_tomcat",     "name": "F-14 Tomcat (قدیمی)",  "category": "Aircraft",     "price": 15_000_000, "initial": 40,   "maint": 40_000, "producible": False},
        {"key": "mig29",          "name": "MiG-29 (وارداتی)",     "category": "Aircraft",     "price": 10_000_000, "initial": 35,   "maint": 30_000, "producible": False},
        {"key": "f4_phantom",     "name": "F-4 Phantom II (قدیمی)","category":"Aircraft",     "price": 6_000_000,  "initial": 60,   "maint": 20_000, "producible": False},
        {"key": "f5_tiger",       "name": "F-5 Tiger (قدیمی)",    "category": "Aircraft",     "price": 4_000_000,  "initial": 60,   "maint": 10_000, "producible": False},
        {"key": "su24",           "name": "Su-24 Fencer (وارداتی)","category":"Aircraft",     "price": 10_000_000, "initial": 30,   "maint": 30_000, "producible": False},
        {"key": "su35_iran",      "name": "Su-35 (وارداتی)",      "category": "Aircraft",     "price": 15_000_000, "initial": 24,   "maint": 45_000, "producible": False},
        {"key": "mirage_f1",      "name": "Mirage F1 (وارداتی)",  "category": "Aircraft",     "price": 5_000_000,  "initial": 20,   "maint": 15_000, "producible": False},
        {"key": "su22",           "name": "Su-22 (وارداتی)",      "category": "Aircraft",     "price": 4_000_000,  "initial": 10,   "maint": 10_000, "producible": False},
        {"key": "c130_iran",      "name": "C-130 Hercules (قدیمی)","category":"Aircraft",     "price": 6_000_000,  "initial": 20,   "maint": 15_000, "producible": False},
        {"key": "il76_iran",      "name": "Il-76 Transporter (وارداتی)","category":"Aircraft","price":15_000_000,  "initial": 10,   "maint": 35_000, "producible": False},
        {"key": "recon_planes",   "name": "شناسایی و آموزشی (قدیمی)","category":"Aircraft",  "price": 2_000_000,  "initial": 30,   "maint": 5_000,  "producible": False},
        {"key": "mi8_mi17",       "name": "Mi-8/Mi-17 (وارداتی)", "category": "Aircraft",     "price": 3_000_000,  "initial": 100,  "maint": 8_000,  "producible": False},
        {"key": "ah1j_cobra",     "name": "AH-1J Cobra (قدیمی)",  "category": "Aircraft",     "price": 4_000_000,  "initial": 30,   "maint": 10_000, "producible": False},
        {"key": "ch47_iran",      "name": "CH-47 Chinook (قدیمی)","category": "Aircraft",     "price": 6_000_000,  "initial": 20,   "maint": 15_000, "producible": False},
        {"key": "bell_214",       "name": "Bell 214 (قدیمی)",     "category": "Aircraft",     "price": 2_000_000,  "initial": 30,   "maint": 5_000,  "producible": False},
        {"key": "light_helis",    "name": "بالگرد سبک (قدیمی)",   "category": "Aircraft",     "price": 1_500_000,  "initial": 100,  "maint": 3_000,  "producible": False},
        {"key": "t72_tank",       "name": "تانک T-72 (وارداتی)",  "category": "Ground Forces","price": 1_500_000,  "initial": 600,  "maint": 4_000,  "producible": False},
        {"key": "t62_tank",       "name": "تانک T-62 (قدیمی)",    "category": "Ground Forces","price": 800_000,    "initial": 400,  "maint": 2_000,  "producible": False},
        {"key": "t55_tank",       "name": "تانک T-55 (قدیمی)",    "category": "Ground Forces","price": 500_000,    "initial": 300,  "maint": 1_000,  "producible": False},
        {"key": "bmp1_bmp2",      "name": "BMP-1 / BMP-2 (قدیمی)","category":"Ground Forces", "price": 600_000,    "initial": 800,  "maint": 1_500,  "producible": False},
        {"key": "apc_iran",       "name": "نفربر زرهی (قدیمی)",   "category": "Ground Forces","price": 400_000,    "initial": 1500, "maint": 1_000,  "producible": False},
        {"key": "tactical_veh",   "name": "خودرو تاکتیکی (قدیمی)", "category": "Ground Forces","price": 100_000,    "initial": 3000, "maint": 300,    "producible": False},
        {"key": "sp_artillery",   "name": "توپخانه خودکششی (قدیمی)","category":"Artillery",  "price": 1_000_000,  "initial": 250,  "maint": 3_000,  "producible": False},
        {"key": "towed_artillery","name": "توپخانه کششی (قدیمی)",  "category": "Artillery",    "price": 300_000,    "initial": 1500, "maint": 800,    "producible": False},
        {"key": "bm21_grad",      "name": "BM-21 Grad (وارداتی)", "category": "Artillery",    "price": 500_000,    "initial": 300,  "maint": 1_200,  "producible": False},
        {"key": "alvand_frigate", "name": "ناوچه کلاس الوند (قدیمی)","category":"Navy",       "price": 10_000_000, "initial": 3,    "maint": 30_000, "producible": False},
        {"key": "kilo_sub",       "name": "زیردریایی کلاس کیلو (وارداتی)","category":"Navy",  "price": 25_000_000, "initial": 3,    "maint": 90_000, "producible": False},
        {"key": "s300_iran",      "name": "S-300PMU-2 (وارداتی)", "category": "Air Defense",  "price": 12_000_000, "initial": 10,   "maint": 35_000, "producible": False},
        {"key": "tor_m1",         "name": "Tor-M1 (وارداتی)",     "category": "Air Defense",  "price": 6_000_000,  "initial": 30,   "maint": 18_000, "producible": False},
        {"key": "short_range_def","name": "پدافند کوتاه‌برد (قدیمی)","category":"Air Defense", "price": 1_000_000,  "initial": 300,  "maint": 3_000,  "producible": False},
        {"key": "radars_iran",    "name": "رادارهای نظامی (قدیمی)","category":"Air Defense",  "price": 3_000_000,  "initial": 200,  "maint": 10_000, "producible": False},
    ],

    # 🇩🇪 جمهوری فدرال آلمان (GERMANY)
    "germany": [
        # بومی (producible=True)
        {"key": "eurofighter",     "name": "Eurofighter Typhoon",  "category": "Aircraft",     "price": 18_000_000, "initial": 138,  "maint": 50_000, "producible": True},
        {"key": "tornado_ecr",    "name": "Tornado IDS/ECR",      "category": "Aircraft",     "price": 10_000_000, "initial": 85,   "maint": 30_000, "producible": True},
        {"key": "tiger_heli",     "name": "Eurocopter Tiger",     "category": "Aircraft",     "price": 8_000_000,  "initial": 50,   "maint": 20_000, "producible": True},
        {"key": "nh90_heli",      "name": "NH90 Helicopter",      "category": "Aircraft",     "price": 6_000_000,  "initial": 80,   "maint": 15_000, "producible": True},
        {"key": "h145m_heli",     "name": "H145M Light Attack",   "category": "Aircraft",     "price": 3_000_000,  "initial": 30,   "maint": 8_000,  "producible": True},
        {"key": "heron1",          "name": "Heron 1 UAV",          "category": "UAV",          "price": 1_000_000,  "initial": 20,   "maint": 3_000,  "producible": True},
        {"key": "recon_drones",   "name": "Tactical Recon UAVs",  "category": "UAV",          "price": 400_000,    "initial": 100,  "maint": 1_000,  "producible": True},
        {"key": "leopard_2a6",    "name": "Leopard 2A6 Tank",     "category": "Ground Forces","price": 3_500_000,  "initial": 150,  "maint": 8_000,  "producible": True},
        {"key": "leopard_2a7",    "name": "Leopard 2A7 Tank",     "category": "Ground Forces","price": 4_500_000,  "initial": 100,  "maint": 10_000, "producible": True},
        {"key": "leopard_2a8",    "name": "Leopard 2A8 Tank",     "category": "Ground Forces","price": 5_500_000,  "initial": 20,   "maint": 12_000, "producible": True},
        {"key": "puma_ifv",       "name": "Puma IFV",             "category": "Ground Forces","price": 2_000_000,  "initial": 300,  "maint": 5_000,  "producible": True},
        {"key": "boxer_apc",      "name": "Boxer Armored Vehicle","category": "Ground Forces","price": 1_500_000,  "initial": 400,  "maint": 3_500,  "producible": True},
        {"key": "marder_ifv",     "name": "Marder 1A5 IFV",       "category": "Ground Forces","price": 1_000_000,  "initial": 300,  "maint": 2_500,  "producible": True},
        {"key": "fuchs_apc",      "name": "Fuchs Vehicle",        "category": "Ground Forces","price": 600_000,    "initial": 600,  "maint": 1_500,  "producible": True},
        {"key": "pzh_2000",       "name": "PzH 2000 Howitzer",    "category": "Artillery",    "price": 2_500_000,  "initial": 100,  "maint": 6_000,  "producible": True},
        {"key": "f125_frigate",   "name": "F125 Baden-Württemberg","category": "Navy",        "price": 25_000_000, "initial": 4,    "maint": 80_000, "producible": True},
        {"key": "f124_frigate",   "name": "F124 Sachsen Class",   "category": "Navy",         "price": 20_000_000, "initial": 3,    "maint": 70_000, "producible": True},
        {"key": "f123_frigate",   "name": "F123 Brandenburg Class","category": "Navy",        "price": 15_000_000, "initial": 4,    "maint": 50_000, "producible": True},
        {"key": "k130_corvette",  "name": "K130 Braunschweig",    "category": "Navy",         "price": 10_000_000, "initial": 5,    "maint": 30_000, "producible": True},
        {"key": "type_212a_sub",  "name": "Type 212A Submarine",  "category": "Navy",         "price": 30_000_000, "initial": 6,    "maint": 120_000,"producible": True},
        {"key": "taurus_kepd",    "name": "Taurus KEPD 350",      "category": "Missiles",     "price": 2_000_000,  "initial": 150,  "maint": 3_000,  "producible": True},
        {"key": "iris_t_missile", "name": "IRIS-T Air-to-Air",    "category": "Missiles",     "price": 500_000,    "initial": 300,  "maint": 800,    "producible": True},
        {"key": "iris_t_sl",      "name": "IRIS-T SL Surface-to-Air","category": "Missiles", "price": 800_000,    "initial": 200,  "maint": 1_200,  "producible": True},
        {"key": "iris_t_slm",     "name": "IRIS-T SLM System",    "category": "Air Defense",  "price": 8_000_000,  "initial": 6,    "maint": 25_000, "producible": True},
        {"key": "iris_t_sls",     "name": "IRIS-T SLS System",    "category": "Air Defense",  "price": 5_000_000,  "initial": 6,    "maint": 15_000, "producible": True},
        {"key": "ozelot_sys",     "name": "Ozelot Air Defense",   "category": "Air Defense",  "price": 2_000_000,  "initial": 40,   "maint": 5_000,  "producible": True},

        # وارداتی (producible=False)
        {"key": "f35a_germany",   "name": "F-35A (وارداتی)",      "category": "Aircraft",     "price": 15_000_000, "initial": 35,   "maint": 50_000, "producible": False},
        {"key": "a400m",          "name": "A400M Atlas (وارداتی)","category": "Aircraft",     "price": 20_000_000, "initial": 45,   "maint": 40_000, "producible": False},
        {"key": "c130j_germany",  "name": "C-130J (وارداتی)",     "category": "Aircraft",     "price": 8_000_000,  "initial": 7,    "maint": 18_000, "producible": False},
        {"key": "a330_mrtt",      "name": "A330 MRTT (وارداتی)",  "category": "Aircraft",     "price": 25_000_000, "initial": 8,    "maint": 50_000, "producible": False},
        {"key": "a321_isr",       "name": "A321LR (وارداتی)",     "category": "Aircraft",     "price": 15_000_000, "initial": 10,   "maint": 30_000, "producible": False},
        {"key": "recon_trainers", "name": "شناسایی و آموزشی",    "category": "Aircraft",     "price": 3_000_000,  "initial": 30,   "maint": 8_000,  "producible": False},
        {"key": "ch53g_heli",     "name": "CH-53G (وارداتی)",     "category": "Aircraft",     "price": 7_000_000,  "initial": 60,   "maint": 18_000, "producible": False},
        {"key": "heron_tp_germany","name":"Heron TP (وارداتی)",   "category": "UAV",          "price": 3_000_000,  "initial": 10,   "maint": 8_000,  "producible": False},
        {"key": "light_armored_g","name": "خودرو زرهی سبک",       "category": "Ground Forces","price": 400_000,    "initial": 1000, "maint": 1_000,  "producible": False},
        {"key": "m109_germany",   "name": "M109 (وارداتی)",       "category": "Artillery",    "price": 1_200_000,  "initial": 20,   "maint": 3_000,  "producible": False},
        {"key": "mars_2",         "name": "MARS II (وارداتی)",    "category": "Artillery",    "price": 3_000_000,  "initial": 35,   "maint": 8_000,  "producible": False},
        {"key": "himars_germany", "name": "HIMARS (وارداتی)",     "category": "Artillery",    "price": 3_000_000,  "initial": 30,   "maint": 8_000,  "producible": False},
        {"key": "aim120_germany", "name": "AIM-120 (وارداتی)",    "category": "Missiles",     "price": 1_000_000,  "initial": 500,  "maint": 1_000,  "producible": False},
        {"key": "meteor_missile", "name": "Meteor BVR (وارداتی)", "category": "Missiles",     "price": 1_500_000,  "initial": 300,  "maint": 2_000,  "producible": False},
        {"key": "air_ground_mun", "name": "مهمات هوا به زمین",   "category": "Missiles",     "price": 400_000,    "initial": 500,  "maint": 500,    "producible": False},
        {"key": "support_fleet_g","name": "شناورهای پشتیبانی",   "category": "Navy",         "price": 3_000_000,  "initial": 20,   "maint": 10_000, "producible": False},
        {"key": "patriot_germany","name": "پاتریوت PAC-3 (وارداتی)","category":"Air Defense", "price": 10_000_000, "initial": 12,   "maint": 30_000, "producible": False},
        {"key": "radars_germany", "name": "رادارهای نظامی",       "category": "Air Defense",  "price": 4_000_000,  "initial": 100,  "maint": 12_000, "producible": False},
    ],
}

# کاتالوگ عمومی برای سایر کشورها
DEFAULT_COUNTRY_EQUIPMENT = [
    {"key": "gen_fighter",   "name": "جنگنده پیشرفته نسل ۴.۵", "category": "Aircraft",     "price": 10_000_000, "initial": 150, "maint": 25_000, "producible": True},
    {"key": "gen_bomber",    "name": "بمب‌افکن استراتژیک",     "category": "Aircraft",     "price": 25_000_000, "initial": 20,  "maint": 60_000, "producible": True},
    {"key": "gen_missile",   "name": "موشک کروز استراتژیک",   "category": "Missiles",     "price": 2_000_000,  "initial": 500, "maint": 2_000,  "producible": True},
    {"key": "gen_airdef",    "name": "سامانه پدافند موشکی",  "category": "Air Defense",  "price": 10_000_000, "initial": 20,  "maint": 25_000, "producible": True},
    {"key": "gen_uav",       "name": "پهپاد شناسایی-رزمی",  "category": "UAV",          "price": 1_000_000,  "initial": 200, "maint": 3_000,  "producible": True},
    {"key": "gen_frigate",   "name": "ناو محافظ سنگین",       "category": "Navy",         "price": 20_000_000, "initial": 10,  "maint": 80_000, "producible": True},
    {"key": "gen_tank",      "name": "تانک اصلی میدان نبرد",  "category": "Ground Forces","price": 2_000_000,  "initial": 1000,"maint": 5_000,  "producible": True},
    {"key": "gen_artillery", "name": "توپخانه خودکششی",       "category": "Artillery",    "price": 1_500_000,  "initial": 300, "maint": 4_000,  "producible": True},
]

# ===== فروشگاه: ساختمان‌ها =====
BUILDINGS = {
    "house":      {"name": "🏠 ساختمان مسکونی", "price": 1_000_000},
    "office":     {"name": "🏢 ساختمان اداری",   "price": 2_000_000},
    "commercial": {"name": "🏬 ساختمان تجاری",   "price": 3_000_000},
    "hotel":      {"name": "🏨 هتل",             "price": 7_000_000},
    "tower":      {"name": "🏙️ برج تجاری",       "price": 10_000_000},
    "skyscraper": {"name": "🏙️ آسمان‌خراش",      "price": 20_000_000},
}

# ===== فروشگاه: صنعت =====
FACTORIES = {
    "small_factory":    {"name": "🏭 کارخانه کوچک",   "price": 3_000_000},
    "medium_factory":   {"name": "🏭 کارخانه متوسط",  "price": 7_000_000},
    "large_factory":    {"name": "🏭 کارخانه بزرگ",   "price": 15_000_000},
    "industrial_complex": {"name": "🏭 مجتمع صنعتی", "price": 25_000_000},
}

# ===== فروشگاه: انرژی =====
POWER_PLANTS = {
    "fossil_plant":  {"name": "⚡ نیروگاه فسیلی",   "price": 10_000_000},
    "solar_plant":   {"name": "☀️ نیروگاه خورشیدی", "price": 8_000_000},
    "wind_plant":    {"name": "🌬️ نیروگاه بادی",    "price": 10_000_000},
    "hydro_plant":   {"name": "💧 نیروگاه آبی",     "price": 15_000_000},
    "nuclear_plant": {"name": "☢️ نیروگاه هسته‌ای", "price": 50_000_000},
}

ALL_SHOP_ITEMS = {}
for group in (BUILDINGS, FACTORIES, POWER_PLANTS):
    ALL_SHOP_ITEMS.update(group)

# ===== مسیر فایل دیتابیس =====
DB_PATH = os.environ.get("DB_PATH", "game.db")
